package com.webtoapp.core.golang

import android.content.Context
import android.net.ConnectivityManager
import com.webtoapp.core.logging.AppLogger
import java.io.File

internal object GoDnsPatcher {

    private const val TAG = "GoDnsPatcher"

    private const val TERMUX_RESOLV_PATH = "/data/data/com.termux/files/usr/etc/resolv.conf"
    private const val TERMUX_HOSTS_PATH = "/data/data/com.termux/files/usr/etc/hosts"

    fun getResolvConfFile(context: Context): File =
        File(context.filesDir, "etc/resolv.conf")

    fun getHostsFile(context: Context): File =
        File(context.filesDir, "etc/hosts")

    fun patchGoBinaryDnsPaths(context: Context, goBinary: File): Int {
        if (!goBinary.exists()) {
            AppLogger.w(TAG, "Go binary 不存在，跳过 patch: ${goBinary.absolutePath}")
            return 0
        }
        val pkg = context.packageName

        val targetResolv = buildEqualLengthPath(pkg, "/etc/resolv.conf", TERMUX_RESOLV_PATH.length)
            ?: run {
                AppLogger.e(TAG, "packageName 过长，无法等长替换 resolv.conf 路径: $pkg")
                return 0
            }
        val targetHosts = buildEqualLengthPath(pkg, "/etc/hosts", TERMUX_HOSTS_PATH.length)
            ?: run {
                AppLogger.e(TAG, "packageName 过长，无法等长替换 hosts 路径: $pkg")
                return 0
            }

        val replacements = listOf(
            TERMUX_RESOLV_PATH to targetResolv,
            TERMUX_HOSTS_PATH to targetHosts,
        )
        val n = patchBinaryStrings(goBinary, replacements)
        AppLogger.i(
            TAG,
            "Go binary DNS 路径 patch: 替换 $n 处. resolv→$targetResolv  hosts→$targetHosts"
        )
        return n
    }

    fun refreshResolvConf(context: Context) {
        val etcDir = File(context.filesDir, "etc").also { it.mkdirs() }
        val resolvConf = File(etcDir, "resolv.conf")

        val nameservers = mutableListOf<String>()
        try {
            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            val net = cm.activeNetwork
            if (net != null) {
                cm.getLinkProperties(net)?.dnsServers?.forEach { addr ->
                    addr.hostAddress?.takeIf { it.isNotBlank() }?.let { nameservers += it }
                }
            }
        } catch (e: Exception) {
            AppLogger.w(TAG, "通过 ConnectivityManager 拿系统 DNS 失败", e)
        }

        if (nameservers.isEmpty()) {
            nameservers += listOf("8.8.8.8", "1.1.1.1", "223.5.5.5", "119.29.29.29")
        }

        val content = buildString {
            append("# Generated by web-to-app GoDnsPatcher.\n")
            append("# Re-written before every Go build/mod operation.\n")
            nameservers.forEach { append("nameserver ").append(it).append('\n') }
            append("options timeout:3 attempts:2\n")
        }
        resolvConf.writeText(content)
        AppLogger.d(TAG, "resolv.conf 已刷新: $nameservers → ${resolvConf.absolutePath}")

        val hosts = File(etcDir, "hosts")
        if (!hosts.exists()) {
            hosts.writeText("127.0.0.1 localhost\n::1 localhost\n")
        }
    }

    private fun buildEqualLengthPath(pkg: String, etcAndFile: String, originalLen: Int): String? {
        val prefix = "/data/data/$pkg/files/"

        val tail = etcAndFile.trimStart('/')
        val baseLen = prefix.length + tail.length
        if (baseLen > originalLen) return null
        val padCount = originalLen - baseLen
        return prefix + "/".repeat(padCount) + tail
    }

    private fun patchBinaryStrings(file: File, replacements: List<Pair<String, String>>): Int {
        val bytes = file.readBytes()
        var totalReplaced = 0
        var anyChange = false
        for ((from, to) in replacements) {
            require(from.length == to.length) {
                "replacement must be equal length: ${from.length} vs ${to.length}"
            }
            val fromBytes = from.toByteArray(Charsets.US_ASCII)
            val toBytes = to.toByteArray(Charsets.US_ASCII)
            var i = 0
            while (i <= bytes.size - fromBytes.size) {
                var match = true
                var j = 0
                while (j < fromBytes.size) {
                    if (bytes[i + j] != fromBytes[j]) { match = false; break }
                    j++
                }
                if (match) {
                    System.arraycopy(toBytes, 0, bytes, i, toBytes.size)
                    totalReplaced++
                    anyChange = true
                    i += fromBytes.size
                } else {
                    i++
                }
            }
        }
        if (anyChange) {
            file.writeBytes(bytes)
            file.setExecutable(true, false)
        }
        return totalReplaced
    }
}
