package com.webtoapp.core.agent.session

import java.util.UUID

data class AgentSession(
    val id: String = UUID.randomUUID().toString(),
    val title: String = "",

    val titleAutoGenerated: Boolean = true,

    val messages: List<AgentMessage> = emptyList(),
    val config: SessionConfig = SessionConfig(),

    val planSlugs: List<String> = emptyList(),

    val pinned: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

data class SessionConfig(
    val textModelId: String? = null,
    val imageModelId: String? = null,
    val temperature: Float = 0.7f,
    val maxTurns: Int = 24,

    val customRules: List<String> = emptyList(),

    val contextAppIds: List<Long> = emptyList(),
    val contextModuleIds: List<String> = emptyList(),

    val builtApks: List<PersistedApk> = emptyList()
) {
    /** Null-safe: Gson bypasses the constructor so [builtApks] can be null for old sessions. */
    val builtApksSafe: List<PersistedApk>
        get() = @Suppress("USELESS_CAST") (builtApks as? List<PersistedApk>) ?: emptyList()
}

/**
 * A build artifact (APK) produced during a session, persisted so it survives
 * app restarts. Mirrors [com.webtoapp.core.agent.tool.BuiltApkInfo] but lives
 * in the session layer to avoid a dependency on the tool package.
 */
data class PersistedApk(
    val appId: Long,
    val apkName: String,
    val apkPath: String,
    val sizeBytes: Long,
    val buildMode: String,
    val packageName: String? = null,
    val versionName: String? = null
)

data class AgentMessage(
    val id: String = UUID.randomUUID().toString(),
    val role: Role,
    val content: String,
    val thinking: String? = null,

    val thinkingSegments: List<ThinkingSegmentData> = emptyList(),

    val thinkingDurationMs: Long? = null,
    val toolCalls: List<RecordedToolCall> = emptyList(),

    val producedFiles: List<String> = emptyList(),

    val attachments: List<String> = emptyList(),

    val userAttachments: List<UserAttachment> = emptyList(),

    val mentionedFiles: List<String> = emptyList(),
    val isError: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
) {
    enum class Role { USER, ASSISTANT, SYSTEM }

    /**
     * Null-safe accessor: Gson bypasses the constructor when deserialising, so
     * [thinkingSegments] can be null for messages loaded from older session JSON that
     * predates this field. Treat that the same as an empty list.
     */
    val thinkingSegmentsSafe: List<ThinkingSegmentData>
        get() = @Suppress("USELESS_CAST") (thinkingSegments as? List<ThinkingSegmentData>) ?: emptyList()
}

/**
 * A file the user attached to a message from the composer. The bytes live in the
 * session sandbox at [path] (session-relative); only metadata is persisted here so
 * the sessions blob stays small. [isImage] attachments are also sent to the model
 * as vision input when it is multimodal.
 */
data class UserAttachment(
    val path: String,
    val displayName: String,
    val mimeType: String,
    val isImage: Boolean
)

data class RecordedToolCall(
    val toolCallId: String,
    val name: String,
    val argumentsJson: String,
    val resultPreview: String,
    val ok: Boolean,

    val activity: String? = null
) {
    companion object {

        const val RUNNING_SENTINEL = "__running__"
    }
}

/**
 * One turn's worth of reasoning, persisted so the boundaries survive across drafts
 * and reloads. [id] matches the inline marker (`\u2063TH:id\u2063`) embedded in
 * [AgentMessage.content], letting the timeline renderer interleave thinking blocks
 * with prose and tool calls in the order they actually occurred.
 */
data class ThinkingSegmentData(
    val id: String,
    val content: String,
    val durationMs: Long? = null
)
