package com.webtoapp.core.feature

object FeatureIds {
    const val COMPAT = "feature-compat"
    const val ENGINE_GECKO = "engine-gecko"
    const val PUSH_FCM = "push-fcm"
    const val NOTIFY_CHANNELS = "notify-channels"
    const val NET_TLS_MITM = "net-tls-mitm"
    const val NET_PROXY = "net-proxy"
    const val NET_DOH = "net-doh"
    const val SERVER_NODEJS = "server-nodejs"
    const val SERVER_PHP = "server-php"
    const val SERVER_PYTHON = "server-python"
    const val SERVER_GO = "server-go"
    const val SERVER_WORDPRESS = "server-wordpress"
    const val RUNTIME_LINUX = "runtime-linux"
    const val EXT_MODULES = "ext-modules"
    const val EXT_BUILTINS = "ext-builtins"
    const val EXT_PANEL = "ext-panel"
    const val EXT_CHROME_SCRIPTS = "ext-chrome-scripts"
    const val SHELL_DISGUISE_JS = "shell-disguise-js"
    const val SHELL_MULTIWEB = "shell-multiweb"
    const val SHELL_MEDIA = "shell-media"
    const val SHELL_ACTIVATION = "shell-activation"
    const val SHELL_ANNOUNCEMENT = "shell-announcement"
    const val SHELL_ADBLOCK = "ads-adblock"
    const val SHELL_DISGUISE = "shell-disguise"
    const val SHELL_PRIVACY = "shell-privacy"
    const val SHELL_ERROR_GAMES = "shell-error-games"
    const val SHELL_DEVICE_ACTIONS = "shell-device-actions"
    const val SHELL_FORCEDRUN = "shell-forcedrun"
    const val SHELL_FORCEDRUN_HW = "shell-forcedrun-hw"
    const val SHELL_FLOATING = "shell-floating"
    const val SHELL_BGM = "shell-bgm"
    const val SHELL_TRANSLATE = "shell-translate"
    const val SHELL_TRANSLATE_SCRIPT = "shell-translate-script"
    const val SHELL_AUTOSTART = "shell-autostart"
    const val SHELL_BACKGROUND = "shell-background"
}

const val LITE_FEATURE_API = 1
