#!/usr/bin/env python3
"""
Translate Chinese log messages in AppLogger.* calls inside Kotlin sources.

Mechanical, dictionary-driven translator that operates only inside the body
of `AppLogger.<level>(...)` calls. Each replacement happens inside string
literals; Kotlin template substitutions (`$var` / `${expr}`) and surrounding
syntax are preserved.

The translation table below is curated by hand. Order matters: longer
phrases must come before shorter ones they contain, so the longer one wins.
"""
from __future__ import annotations

import re
import sys
from typing import List, Tuple


TRANSLATIONS: List[Tuple[str, str]] = [
    # ---------- ForcedRunHardwareController ----------
    ("原生能力", "native capability"),
    ("共享热点能力探测失败", "shared-hotspot capability probe failed"),
    ("持续设置音量失败", "Sustained volume control failed"),
    ("持续最大音量已启动（广播监听 + ", "Sustained max volume started (broadcast watcher + "),
    ("ms轮询）", "ms poll)"),
    ("设置音量失败", "Set volume failed"),
    ("音量变化广播接收器已注册", "Volume-change receiver registered"),
    ("音量变化广播接收器已注销", "Volume-change receiver unregistered"),
    ("注销音量广播接收器失败", "Failed to unregister volume receiver"),
    ("音量已恢复", "Volume restored"),
    ("恢复音量失败", "Failed to restore volume"),
    ("当前设备不支持震动，跳过持续震动", "Device has no vibrator, skipping sustained vibration"),
    ("持续震动已启动 (Native)", "Sustained vibration started (Native)"),
    ("持续震动已启动 (Java Waveform)", "Sustained vibration started (Java Waveform)"),
    ("持续震动已启动 (Java)", "Sustained vibration started (Java)"),
    ("震动失败", "Vibration failed"),
    ("震动已停止", "Vibration stopped"),
    ("当前设备不支持闪光灯，跳过开启", "Device has no flashlight, skipping turn-on"),
    ("闪光灯已打开 (Native)", "Flashlight on (Native)"),
    ("闪光灯已打开 (Java)", "Flashlight on (Java)"),
    ("打开闪光灯失败", "Failed to turn flashlight on"),
    ("闪光灯已关闭", "Flashlight off"),
    ("关闭闪光灯失败", "Failed to turn flashlight off"),
    ("当前设备不支持闪光灯，跳过爆闪模式", "Device has no flashlight, skipping strobe mode"),
    ("爆闪模式已启动 (Native, 100ms)", "Strobe mode started (Native, 100ms)"),
    ("爆闪模式失败", "Strobe mode failed"),
    ("爆闪模式已启动 (Java)", "Strobe mode started (Java)"),
    ("摩斯电码文本为空", "Morse code text is empty"),
    ("当前设备不支持闪光灯，跳过摩斯电码模式", "Device has no flashlight, skipping Morse code mode"),
    ("摩斯电码已启动 (Native)", "Morse code started (Native)"),
    ("摩斯电码已启动 (Java)", "Morse code started (Java)"),
    ("摩斯电码播放失败", "Morse code playback failed"),
    ("自定义闪烁序列参数无效", "Custom blink pattern arguments invalid"),
    ("当前设备不支持闪光灯，跳过自定义闪烁", "Device has no flashlight, skipping custom blink"),
    ("自定义闪烁已启动 (Native)", "Custom blink started (Native)"),
    ("自定义闪烁播放失败", "Custom blink playback failed"),
    ("自定义闪烁已启动 (Java)", "Custom blink started (Java)"),
    ("步 loop=", "steps loop="),
    ("心跳模式已启动", "Heartbeat mode started"),
    ("呼吸灯模式已启动", "Breathing mode started"),
    ("紧急三闪模式已启动", "Emergency triple-flash mode started"),
    ("当前设备不支持原生性能模式，跳过最大性能模式",
        "Device doesn't support native perf mode, skipping max performance"),
    ("最大性能模式已启动 (Native CPU burn + governor)",
        "Max performance mode started (Native CPU burn + governor)"),
    ("最大性能模式已停止", "Max performance mode stopped"),
    ("应用缓存已清理", "App cache cleared"),
    ("清理缓存失败", "Failed to clear cache"),
    ("持续设置静音失败", "Sustained mute control failed"),
    ("持续静音模式已启动（广播监听 + ", "Sustained mute mode started (broadcast watcher + "),
    ("设置静音模式失败", "Failed to set mute mode"),
    ("静音模式音量广播接收器已注册", "Mute-mode volume receiver registered"),
    ("静音模式音量广播接收器已注销", "Mute-mode volume receiver unregistered"),
    ("注销静音模式音量广播接收器失败", "Failed to unregister mute-mode volume receiver"),
    ("铃声模式已恢复", "Ringer mode restored"),
    ("恢复铃声模式失败", "Failed to restore ringer mode"),
    ("屏幕常亮已启用", "Keep-screen-on enabled"),
    ("设置屏幕常亮失败", "Failed to enable keep-screen-on"),
    ("屏幕常亮已释放", "Keep-screen-on released"),
    ("释放屏幕常亮失败", "Failed to release keep-screen-on"),
    ("屏幕翻转失败", "Screen flip failed"),
    ("屏幕四向循环翻转已启动", "Four-way screen-flip cycle started"),
    ("辅助功能未启用，无法屏蔽音量键",
        "Accessibility service not enabled, can't block volume keys"),
    ("音量键屏蔽已启用 (AccessibilityService)",
        "Volume-key block enabled (AccessibilityService)"),
    ("音量键屏蔽已禁用", "Volume-key block disabled"),
    ("辅助功能未启用，无法屏蔽电源键",
        "Accessibility service not enabled, can't block power key"),
    ("电源键屏蔽已启用 (SCREEN_OFF 防护)",
        "Power-key block enabled (SCREEN_OFF protection)"),
    ("电源键屏蔽已禁用", "Power-key block disabled"),
    ("辅助功能未启用，无法屏蔽触摸",
        "Accessibility service not enabled, can't block touch"),
    ("触摸屏蔽已启用 (ACCESSIBILITY_OVERLAY)",
        "Touch block enabled (ACCESSIBILITY_OVERLAY)"),
    ("触摸屏蔽已禁用", "Touch block disabled"),
    ("辅助功能未启用，黑屏模式将降级为亮度压暗",
        "Accessibility service not enabled, blackout will degrade to brightness dim"),
    ("全黑屏模式已启用（按可用能力降级）",
        "Full blackout mode enabled (degraded by capability)"),
    ("当前设备无法启用黑屏模式", "Device can't enable blackout mode"),
    ("恢复系统亮度失败", "Failed to restore system brightness"),
    ("全黑屏模式已禁用", "Full blackout mode disabled"),
    ("热点已在运行中", "Hotspot already running"),
    ("当前系统不支持应用侧热点控制，跳过开启热点",
        "OS doesn't support app-side hotspot control, skipping hotspot start"),
    ("已关闭 WiFi 以开启热点", "WiFi turned off to start hotspot"),
    ("仅检测到 LocalOnlyHotspot，不能替代共享热点，已跳过",
        "Only LocalOnlyHotspot is available; can't replace shared hotspot, skipping"),
    ("开启热点失败", "Failed to start hotspot"),
    ("热点已开启 (Legacy)", "Hotspot started (Legacy)"),
    ("Legacy 热点开启失败", "Legacy hotspot start failed"),
    (" 无稳定共享热点接口，已跳过", " has no stable shared-hotspot API, skipping"),
    ("TetheringManager 不可用，无法开启共享热点",
        "TetheringManager unavailable, can't start shared hotspot"),
    ("Android 11+ 公开热点接口无法稳定自定义 SSID/密码，将使用系统热点配置",
        "Android 11+ public hotspot API can't reliably customise SSID/password, "
        "falling back to system hotspot configuration"),
    ("共享热点已开启（系统配置）", "Shared hotspot started (system configuration)"),
    ("共享热点开启失败", "Shared hotspot start failed"),
    ("共享热点权限不足", "Insufficient permission for shared hotspot"),
    ("LocalOnlyHotspot 已开启", "LocalOnlyHotspot started"),
    ("LocalOnlyHotspot 已停止", "LocalOnlyHotspot stopped"),
    ("LocalOnlyHotspot 失败", "LocalOnlyHotspot failed"),
    ("LocalOnlyHotspot 开启失败", "LocalOnlyHotspot start failed"),
    ("共享热点已关闭", "Shared hotspot stopped"),
    ("共享热点关闭失败", "Shared hotspot stop failed"),
    ("关闭共享热点权限不足", "Insufficient permission to stop shared hotspot"),
    ("Legacy 热点关闭反射失败", "Legacy hotspot stop (reflection) failed"),
    ("热点已关闭", "Hotspot stopped"),
    ("关闭热点失败", "Failed to stop hotspot"),
    (" 不支持第三方应用直接关闭 WiFi，已跳过",
        " doesn't allow third-party apps to disable WiFi directly, skipping"),
    ("WiFi 已强制关闭", "WiFi force-disabled"),
    ("关闭 WiFi 失败", "Failed to disable WiFi"),
    ("WiFi 已恢复", "WiFi restored"),
    ("恢复 WiFi 失败", "Failed to restore WiFi"),
    ("当前系统不支持第三方应用直接关闭蓝牙，已跳过",
        "OS doesn't allow third-party apps to disable Bluetooth, skipping"),
    ("蓝牙已强制关闭", "Bluetooth force-disabled"),
    ("关闭蓝牙失败", "Failed to disable Bluetooth"),
    ("蓝牙已恢复", "Bluetooth restored"),
    ("恢复蓝牙失败", "Failed to restore Bluetooth"),
    ("当前应用缺少移动数据控制所需特权，已跳过",
        "Missing privilege required to control mobile data, skipping"),
    ("移动数据已处于关闭状态", "Mobile data already disabled"),
    ("移动数据已强制关闭", "Mobile data force-disabled"),
    ("关闭移动数据失败（需要 carrier privilege 或系统权限）",
        "Failed to disable mobile data (needs carrier privilege or system permission)"),
    ("当前设备无 TelephonyManager，已跳过移动数据控制",
        "Device has no TelephonyManager, skipping mobile data control"),
    ("当前设备无 TelephonyManager，跳过移动数据恢复",
        "Device has no TelephonyManager, skipping mobile data restore"),
    ("移动数据已恢复", "Mobile data restored"),
    ("恢复移动数据失败（需要 carrier privilege 或系统权限）",
        "Failed to restore mobile data (needs carrier privilege or system permission)"),
    ("恢复移动数据失败", "Failed to restore mobile data"),
    ("自定义警报序列无效 (需要偶数个参数)",
        "Custom alarm pattern invalid (needs even number of arguments)"),
    ("自定义警报震动失败", "Custom alarm vibration failed"),
    ("自定义警报已启动", "Custom alarm started"),
    (" 步, vibSync=", " steps, vibSync="),
    ("黑科技功能未启用", "Stealth feature not enabled"),
    ("当前设备没有可执行的黑科技特性，跳过启动",
        "Device has no executable stealth features, skipping start"),
    ("启动黑科技功能", "Starting stealth features"),
    ("停止所有黑科技功能", "Stopping all stealth features"),
    ("黑科技特性已按当前设备能力降级",
        "Stealth features degraded to match current device capability"),
    # ---------- JarSigner ----------
    ("成功使用 PKCS12 密钥方案", "Successfully using PKCS12 key scheme"),
    ("成功从 Android KeyStore 加载密钥",
        "Successfully loaded key from Android KeyStore"),
    ("成功生成 Android KeyStore 密钥",
        "Successfully generated Android KeyStore key"),
    ("从 Android KeyStore 加载密钥失败",
        "Failed to load key from Android KeyStore"),
    ("删除了旧的 KeyStore 条目", "Deleted stale KeyStore entry"),
    ("删除旧密钥失败（可忽略）", "Failed to delete stale key (safe to ignore)"),
    ("生成 Android KeyStore 密钥失败",
        "Failed to generate Android KeyStore key"),
    ("加载自定义 PKCS12 失败", "Failed to load custom PKCS12"),
    ("证书已过期或无效", "Certificate expired or invalid"),
    (")，重新生成...", "), regenerating..."),
    ("从自动生成的 PKCS12 加载成功，有效期至 ",
        "Loaded auto-generated PKCS12 successfully, valid until "),
    ("自动 PKCS12 密钥方案失败", "Auto PKCS12 key scheme failed"),
    ("读取密码文件失败", "Failed to read password file"),
    ("迁移旧密码到文件存储", "Migrating legacy password to file storage"),
    ("保存密码文件失败", "Failed to save password file"),
    ("PKCS12 中找不到密钥条目（alias=", "No key entry in PKCS12 (alias="),
    (") 失败 —— keypass 可能与 storepass 不同",
        ") failed — keypass might differ from storepass"),
    ("从 PKCS12 加载成功", "Loaded successfully from PKCS12"),
    ("加载 PKCS12 失败", "Failed to load PKCS12"),
    ("创建新的 PKCS12 密钥库...", "Creating new PKCS12 keystore..."),
    ("RSA 密钥对已生成", "RSA key pair generated"),
    ("Android KeyStore 证书生成失败，使用手写 ASN.1 回退",
        "Android KeyStore certificate generation failed, falling back to manual ASN.1"),
    ("创建 PKCS12 成功", "PKCS12 created successfully"),
    (", 有效期至 ", ", valid until "),
    ("通过 Android KeyStore 模板生成证书成功",
        "Certificate generated via Android KeyStore template"),
    ("清理临时 KeyStore 条目失败（可忽略）",
        "Failed to clean up temporary KeyStore entry (safe to ignore)"),
    ("导入失败: PKCS12 中找不到密钥",
        "Import failed: no key entry in PKCS12"),
    ("导入自定义 PKCS12 成功", "Custom PKCS12 import successful"),
    ("导入 PKCS12 失败", "PKCS12 import failed"),
    (" 中找不到密钥条目，跳过", " has no key entry, skipping"),
    (" 中密钥或证书为空", " has empty key or certificate"),
    (" 转换为 PKCS12 并保存（统一 storepass==keypass）",
        " converted to a unified-password PKCS12 (storepass==keypass) and saved"),
    ("已将 ", "Converted "),
    ("导入自定义签名文件成功 (原始格式: ",
        "Custom signature file imported (original format: "),
    ("尝试以 ", "Attempting to parse as "),
    (" 格式解析失败", " failed"),
    ("所有格式均无法解析此签名文件",
        "Couldn't parse signature file in any supported format"),
    ("成功以 ", "Successfully parsed signature file as "),
    (" 格式解析签名文件", ""),
    ("导出失败: 没有可用的密钥", "Export failed: no key available"),
    ("导出 PKCS12 成功", "PKCS12 exported successfully"),
    ("导出 PKCS12 失败", "PKCS12 export failed"),
    ("已删除自定义 PKCS12 和 sidecar，回退到",
        "Removed custom PKCS12 and sidecar, falling back to"),
    ("删除自定义 PKCS12 失败", "Failed to delete custom PKCS12"),
    ("密钥或证书为空，尝试重新初始化...",
        "Key or certificate is empty, retrying initialisation..."),
    ("开始签名 APK", "Signing APK"),
    ("签名类型", "Signer type"),
    ("输入 APK 不存在", "Input APK doesn't exist"),
    ("输入 APK 文件为空", "Input APK file is empty"),
    ("无法读取输入 APK", "Can't read input APK"),
    ("无法创建输出目录", "Can't create output directory"),
    ("尝试签名方案", "Trying signing scheme"),
    ("签名成功", "Signed successfully"),
    (" 校验未通过，回落到更保守的签名方案",
        " verification failed, falling back to a more conservative scheme"),
    ("签名异常 ", "Signing exception "),
    ("完整堆栈:", "Full stack trace:"),
    ("检测到可能的密钥问题，重新生成...",
        "Possible key issue detected, regenerating..."),
    ("所有签名方案均失败", "All signing schemes failed"),
    ("证书:", "Certificate:"),
    ("密钥:", "Key:"),
    ("证书有效期", "Certificate validity"),
    ("签名配置", "Signing config"),
    ("调用 ApkSigner.sign()...", "Calling ApkSigner.sign()..."),
    ("ApkSigner.sign() 完成", "ApkSigner.sign() complete"),
    ("签名后输出文件不存在或为空",
        "Signed output file is missing or empty"),
    ("签名输出", "Signed output"),
    ("ApkSigner 签名", "ApkSigner: signing"),
    ("ApkSigner 异常", "ApkSigner exception"),
    ("ApkSigner: 输出文件无效", "ApkSigner: output file is invalid"),
    ("V1 签名验证失败，APK 签名无效",
        "V1 signature verification failed, APK signature is invalid"),
    ("V1 签名", "V1 signing"),
    ("签名验证失败", "Signature verification failed"),
    ("证书未初始化", "Certificate not initialised"),
    ("私钥为空", "Private key is empty"),
    ("证书为空", "Certificate is empty"),
    # ---------- WebViewActivity ----------
    ("找不到 webApp", "webApp not found"),
    ("处理图片下载请求", "Handling image download request"),
    ("处理 blob URL", "Handling blob URL"),
    ("blob URL 处理失败", "blob URL handling failed"),
    ("图片下载失败", "Image download failed"),
    ("无法保存图片", "Can't save image"),
    ("图片已保存", "Image saved"),
    ("无法获取图片字节", "Can't fetch image bytes"),
    ("图片下载请求", "Image download request"),
    ("收到 file://", "Received file://"),
    ("URL 无效", "URL is invalid"),
    ("用户已取消下载", "User cancelled download"),
    ("尝试启动下载: ", "Attempting download: "),
    ("启动失败", "Launch failed"),
    ("下载启动失败", "Download start failed"),
    ("下载完成: ", "Download complete: "),
    ("下载已加入队列: ", "Download enqueued: "),
    ("解析 dataUri 失败", "Failed to parse dataUri"),
    ("应用已激活，跳过激活码", "App already activated, skipping activation code"),
    ("公告已设置", "Announcement configured"),
    ("公告设置失败", "Announcement setup failed"),
    ("WebApp 未配置激活", "WebApp has no activation configured"),
    ("已激活，跳过", "Already activated, skipping"),
    ("启动激活流程", "Starting activation flow"),
    ("激活成功", "Activation succeeded"),
    ("激活失败", "Activation failed"),
    ("激活已取消", "Activation cancelled"),
    ("WebApp 启动", "WebApp launched"),
    ("跳转到首页", "Redirecting to home"),
    ("WebApp 关闭", "WebApp closed"),
    ("退出全屏", "Exiting fullscreen"),
    ("进入全屏", "Entering fullscreen"),
    ("WebView 加载: ", "WebView load: "),
    ("WebView 加载完成: ", "WebView load complete: "),
    ("WebView 加载错误: ", "WebView load error: "),
    ("WebView 错误", "WebView error"),
    ("收到 SSL 错误", "SSL error received"),
    ("SSL 错误已忽略", "SSL error ignored"),
    ("自定义错误页加载失败", "Custom error page load failed"),
    ("用户取消了 SSL 警告", "User cancelled SSL warning"),
    ("已检测到广告，已拦截", "Ad detected and blocked"),
    ("加载完成", "Load complete"),
    ("注入扩展模块", "Injecting extension module"),
    ("扩展模块注入失败", "Extension module injection failed"),
    ("注入广告屏蔽脚本", "Injecting ad-block script"),
    ("Cookie 已清理", "Cookies cleared"),
    ("缓存已清理", "Cache cleared"),
    ("启动 OAuth 流程", "Starting OAuth flow"),
    ("OAuth 回调", "OAuth callback"),
    ("OAuth 失败", "OAuth failed"),
    # ---------- ShellServerModes ----------
    ("projectId 为空", "projectId is empty"),
    ("项目目录", "Project directory"),
    ("找到 docRoot", "Found docRoot"),
    ("检查候选", "Checking candidate"),
    ("LocalHttpServer 已启动", "LocalHttpServer started"),
    ("启动预览失败", "Failed to start preview"),
    ("已存在提取标记, 跳过提取", "Extraction marker exists, skipping extraction"),
    ("根目录未找到入口文件，扫描子目录...",
        "No entry file at root, scanning subdirectories..."),
    ("回退到预览模式", "Falling back to preview mode"),
    ("Node.js 启动失败", "Node.js failed to start"),
    ("Python 启动失败", "Python failed to start"),
    ("PHP 启动失败", "PHP failed to start"),
    ("Go 启动失败", "Go failed to start"),
    ("WordPress 启动失败", "WordPress failed to start"),
    ("提取静态资源失败", "Static asset extraction failed"),
    ("提取 dist 目录", "Extracting dist directory"),
    ("提取完成: ", "Extraction complete: "),
    ("解压完成", "Unpack complete"),
    ("ShellServer 已启动", "ShellServer started"),
    ("ShellServer 关闭", "ShellServer shutting down"),
    ("ShellServer 关闭失败", "ShellServer shutdown failed"),
    ("应用关闭，不再回退", "App closed, no further fallback"),
    ("加密资产解密失败", "Encrypted asset decryption failed"),
    ("找不到入口", "Entry point not found"),
    ("LocalHttpServer 关闭", "LocalHttpServer shutting down"),
    ("绑定端口失败", "Port binding failed"),
    ("无可用端口", "No available port"),
    # ---------- PythonDependencyManager ----------
    ("Python 运行时已安装", "Python runtime installed"),
    ("Python 运行时未安装", "Python runtime not installed"),
    ("下载 Python 运行时", "Downloading Python runtime"),
    ("下载失败", "Download failed"),
    ("解压 Python 运行时", "Extracting Python runtime"),
    ("解压失败", "Extraction failed"),
    ("Python 运行时已就绪", "Python runtime ready"),
    ("Python 运行时下载失败", "Python runtime download failed"),
    ("Python 安装失败", "Python install failed"),
    ("Python 解压完成", "Python extraction complete"),
    ("Python 已安装但 CRC 校验失败，正在重新下载",
        "Python installed but CRC failed, re-downloading"),
    ("CRC 校验通过", "CRC check passed"),
    ("CRC 校验失败", "CRC check failed"),
    ("校验通过", "Check passed"),
    ("校验失败", "Check failed"),
    ("找不到 Python 入口", "Can't find Python entry point"),
    ("找不到 pip 二进制", "Can't find pip binary"),
    ("pip install 失败", "pip install failed"),
    ("pip install 完成", "pip install complete"),
    ("requirements.txt 不存在", "requirements.txt not found"),
    ("移除旧的 venv", "Removing old venv"),
    ("创建 venv 失败", "venv creation failed"),
    ("venv 创建成功", "venv created"),
    ("当前架构不支持", "Current ABI not supported"),
    ("当前 ABI", "Current ABI"),
    ("不支持的 ABI: ", "Unsupported ABI: "),
    ("总大小: ", "Total size: "),
    (" 字节", " bytes"),
    ("下载完成", "Download complete"),
    ("从缓存恢复", "Restored from cache"),
    ("无效的下载 URL", "Invalid download URL"),
    ("HTTP 错误", "HTTP error"),
    ("已存在", "Already exists"),
    ("正在下载", "Downloading"),
    ("已下载: ", "Downloaded: "),
    # ---------- Round 2: carry-over fragments + new files ----------

    # ForcedRunHardwareController carry-overs
    ("关闭Insufficient permission for shared hotspot",
        "Insufficient permission to stop shared hotspot"),
    ("自定义警报Vibration failed", "Custom alarm vibration failed"),

    # JarSigner round 2
    ("[$source] 开始校验 APK", "[$source] Verifying APK"),
    ("[$source] APK 验证完成", "[$source] APK verification complete"),
    ("[$source] 验证问题", "[$source] Verification issue"),
    ("[$source] 验证警告", "[$source] Verification warning"),
    ("[$source] ApkVerifier 报告未通过验证，但 APK 文件结构完整，",
        "[$source] ApkVerifier flagged a verification failure, but the APK file structure is intact; "),
    ("大多数情况下仍可正常安装。skipping验证拦截。",
        "the APK should still install on most devices. Skipping the verification gate."),
    ("[$source] 验证过程异常（不影响构建）",
        "[$source] Verification raised an exception (build is unaffected)"),
    ("重置所有签名密钥...", "Resetting all signing keys..."),
    ("已删除 Android KeyStore 密钥", "Android KeyStore key deleted"),
    ("删除 Android KeyStore 密钥failed", "Failed to delete Android KeyStore key"),
    ("密钥重置完成，当前类型", "Key reset complete, current signer type"),
    ("重置密钥failed", "Key reset failed"),

    # WebViewActivity carry-overs and PHP/Python/NodeJs/Go preview blocks
    ("开始 PHP 应用预览流程", "Starting PHP app preview flow"),
    ("phpAppConfig 为 null，无法启动预览",
        "phpAppConfig is null, can't start preview"),
    ("检查 PHP 依赖", "Checking PHP runtime"),
    ("入口文件不存在，尝试自动检测框架...",
        "Entry file missing, attempting auto-detection..."),
    ("找到 PHP 子目录", "Found PHP subdirectory"),
    ("自动检测", "Auto-detected"),
    ("启动 PHP 服务器", "Starting PHP server"),
    ("PHP 服务器started", "PHP server started"),
    ("PHP 服务器Launch failed", "PHP server failed to start"),
    ("pythonAppConfig 为 null", "pythonAppConfig is null"),
    ("开始 Python 应用预览流程", "Starting Python app preview flow"),
    ("入口文件不存在: ", "Entry file missing: "),
    ("，尝试自动检测...", ", attempting auto-detection..."),
    ("自动检测到", "Auto-detected"),
    ("找到 Python 子目录", "Found Python subdirectory"),
    ("子目录检测", "Subdirectory detection"),
    ("最终配置", "Final configuration"),
    ("Python 运行时可用，启动后端服务器",
        "Python runtime available, starting backend server"),
    ("Python 服务器started", "Python server started"),
    ("Python 服务器Launch failed", "Python server failed to start"),
    ("Python 运行时不可用，生成项目预览页面",
        "Python runtime unavailable, generating project preview page"),
    ("nodejsConfig 为 null", "nodejsConfig is null"),
    ("开始 Node.js 应用预览流程", "Starting Node.js app preview flow"),
    ("已从源目录同步 Node 项目", "Synced Node.js project from source directory"),
    ("同步源项目failed", "Failed to sync source project"),
    ("未找到 index.html，尝试在项目根启动 HTTP 服务器",
        "index.html not found, trying HTTP server at project root"),
    ("LocalHttpServer 在项目根启动",
        "LocalHttpServer started at project root"),
    ("找到 HTML 文件", "Found HTML file"),
    ("无静态 HTML，生成项目预览页面",
        "No static HTML, generating project preview page"),
    ("预览页面已生成", "Preview page generated"),
    ("goAppConfig 为 null", "goAppConfig is null"),
    ("开始 Go 应用预览流程", "Starting Go app preview flow"),
    ("启动 Go 后端服务器（仅使用预编译二进制）",
        "Starting Go backend server (precompiled binary only)"),
    ("Go 服务器started", "Go server started"),
    ("Go 服务器Launch failed", "Go server failed to start"),
    ("无可执行二进制，生成项目预览页面",
        "No executable binary, generating project preview page"),
    ("，Falling back to preview mode", ", falling back to preview mode"),
    ("目录文件列表", "Directory file list"),
    (" 个):", "):"),
    ("入口文件路径", "Entry file path"),
    ("入口文件存在", "Entry file exists"),
    ("目标 URL", "Target URL"),
    ("启动本地服务器failed", "Failed to start local server"),
    ("HTMLProject directory不存在", "HTML project directory does not exist"),

    # ShellServerModes round 2
    ("提取 WordPress 文件到 ", "Extracting WordPress files to "),
    ("WordPress 就绪", "WordPress ready"),
    ("提取 HTML 资源到 ", "Extracting HTML assets to "),
    ("HTML Shell 就绪", "HTML Shell ready"),
    ("libnode.so 未找到", "libnode.so not found"),
    ("libnode.so 路径", "libnode.so path"),
    ("提取 Node.js 项目文件到 ", "Extracting Node.js project files to "),
    ("Node.js 就绪", "Node.js ready"),
    ("首次运行，提取 Python 标准库到 ",
        "First run, extracting Python stdlib to "),
    ("Python 标准库提取完成", "Python stdlib extraction complete"),
    ("assets/python_runtime 不存在或为空，尝试 legacy assets/python/ 路径",
        "assets/python_runtime missing or empty, trying legacy assets/python/ path"),
    ("Legacy: Python 二进制已提取到 ", "Legacy: Python binary extracted to "),
    ("Legacy Python 二进制提取failed", "Legacy Python binary extraction failed"),
    ("提取 Python 标准库failed", "Failed to extract Python stdlib"),
    ("Python 标准库已提取，skipping", "Python stdlib already extracted, skipping"),
    ("Python 运行时不可用，Falling back to preview mode",
        "Python runtime unavailable, falling back to preview mode"),
    ("提取 Python 项目文件到 ", "Extracting Python project files to "),
    ("Python 服务器就绪", "Python server ready"),
    ("Python 服务器Launch failed", "Python server failed to start"),
    ("提取 Go 项目文件到 ", "Extracting Go project files to "),
    ("未检测到 Go 二进制，Falling back to preview mode",
        "Go binary not detected, falling back to preview mode"),
    ("检测到 Go 二进制", "Go binary detected"),
    ("Go 服务器就绪", "Go server ready"),
    ("Go 服务器Launch failed", "Go server failed to start"),
    (" Shell 启动 ", " Shell start "),
    ("Python配置", "Python config"),
    ("Python环境变量", "Python env vars"),
    ("Go配置", "Go config"),
    (" 内容 (", " contents ("),
    (" 项): ", " items): "),
    ("为空或不存在!", "is empty or missing!"),
    ("列出 ", "Listing "),
    ("首次提取: 删除旧目录并从 assets 提取...",
        "First extract: removing old directory and extracting from assets..."),
    ("提取完成, marker 已创建", "Extraction complete, marker created"),
    ("提取后目录结构", "Post-extraction directory structure"),
    (" 个文件):\\n", " files):\\n"),
    ("Checking candidate目录", "Checking candidate directory"),
    ("所有候选目录均未找到 index.html",
        "No candidate directory contains index.html"),
    ("回退到 file:// 模式", "Falling back to file:// mode"),
    ("最终failed: siteDir 中也没有 index.html",
        "Final failure: siteDir also lacks index.html"),
    ("Python/Go 后端应用需要对应运行时才能提供页面，当前实现仅支持静态前端产物",
        "Python/Go backend apps need their runtime to serve pages; "
        "this implementation only supports static frontend artefacts"),
    ("最终状态", "Final status"),
    ("启动异常", "Start exception"),
    ("WebView ready, 即将加载 URL",
        "WebView ready, about to load URL"),

    # PythonDependencyManager round 2
    ("使用 Python: ", "Using Python: "),
    ("使用下载目录 Python (fallback): ",
        "Using downloaded Python (fallback): "),
    ("Python 运行时Download complete", "Python runtime download complete"),
    ("无 requirements.txt，skipping依赖安装",
        "No requirements.txt, skipping dependency install"),
    ("构建阶段缺少可执行 musl linker，无法预安装 Python 依赖",
        "musl linker missing at build time, can't pre-install Python dependencies"),
    ("Python 依赖安装succeeded", "Python dependency install succeeded"),
    ("Python 依赖安装failed", "Python dependency install failed"),
    ("安装 Python 依赖异常", "Python dependency install exception"),
    ("检测到 Android 不兼容的 Python 依赖，已改用清洗后的 requirements",
        "Detected Android-incompatible Python dependencies; using sanitised requirements"),
    ("创建 Python wrapper", "Creating Python wrapper"),
    ("安装 Python 依赖 (wrapper模式)", "Installing Python dependencies (wrapper mode)"),
    ("pip --only-binary failed (exitCode=$exitCode)，重试不限制...",
        "pip --only-binary failed (exitCode=$exitCode), retrying without restrictions..."),
    ("安装 Python 依赖 (wrapper模式-重试)",
        "Installing Python dependencies (wrapper-mode retry)"),
    ("安装 Python 依赖 (直接模式)", "Installing Python dependencies (direct mode)"),
    ("executeCommand: 启动进程...", "executeCommand: starting process..."),
    ("pip 输出流读取结束", "pip output stream closed"),
    ("pip install timed out (${PIP_TIMEOUT_SECONDS}秒)，强制终止进程",
        "pip install timed out (${PIP_TIMEOUT_SECONDS}s), force-killing process"),
    ("Python 依赖Cache cleared", "Python dependency cache cleared"),
    ("尝试下载 ", "Attempting to download "),
    ("Download failed, ${RETRY_DELAY_MS / 1000}s 后重试 ($attempt/$MAX_RETRY_PER_URL)",
        "download failed, retrying in ${RETRY_DELAY_MS / 1000}s ($attempt/$MAX_RETRY_PER_URL)"),
    ("failed，切换下一个源...", "failed, trying next source..."),
    ("Downloading Python runtime (共 ", "Downloading Python runtime ("),
    (" 个源)", " sources)"),
    ("复制 python3.12 -> python3 (替代损坏的符号链接)",
        "Copying python3.12 -> python3 (replacing broken symlink)"),
    ("未找到有效的 python3.12 或 python3，搜索其他二进制",
        "No valid python3.12 or python3 found; searching for other binaries"),
    ("Python 二进制已移动到", "Python binary moved to"),
    ("解压后未找到有效的 Python 二进制 (>1MB)",
        "No valid Python binary (>1MB) found after extraction"),
    ("解压 Python failed", "Python extraction failed"),
    ("musl 动态链接器Download failed，Python 可能无法在 Android 上执行",
        "musl dynamic linker download failed; Python may not execute on Android"),
    ("Current ABI ($abi) 无可用的 musl linker",
        "Current ABI ($abi) has no available musl linker"),
    ("下载 musl linker", "Downloading musl linker"),
    ("musl linker 已提取", "musl linker extracted"),
    ("Alpine APK 中未找到 ", "Alpine APK does not contain "),
    ("下载 musl linker failed", "musl linker download failed"),
    ("解压 ${archiveFile.name} 到 ${destDir.absolutePath}",
        "Extracting ${archiveFile.name} to ${destDir.absolutePath}"),
    (" (剥离前缀: $stripPrefix)", " (strip prefix: $stripPrefix)"),
    ("skipping可疑路径", "Skipping suspicious path"),
    ("解析符号链接failed", "Failed to resolve symlink"),
    ("skipping符号链接（目标不存在）",
        "Skipping symlink (target missing)"),
    ("Unpack complete: $fileCount 个文件, $resolvedLinks/${deferredSymlinks.size} 个符号链接已解析",
        "Unpack complete: $fileCount files, $resolvedLinks/${deferredSymlinks.size} symlinks resolved"),

    # ---------- general tail (broad rules go LAST so specific entries above win) ----------
    ("失败: ", "failed: "),
    ("失败", "failed"),
    ("成功", "succeeded"),
    ("已启动", "started"),
    ("已停止", "stopped"),
    ("已关闭", "closed"),
    ("跳过", "skipping"),
    ("初始化", "initialise"),
    ("超时", "timed out"),
    ("启动", "Starting"),
    ("已就绪", "ready"),
    (" 个文件", " files"),
    (" 个", " "),

    # ---------- Phase 3: developer-facing logger phrases ----------
    # These are stems that appear repeatedly across runtime / forcedrun /
    # database / build code paths. Each maps a Chinese sub-phrase to its
    # English equivalent. Order matters: longer / more specific entries
    # belong above broader ones so the broader rule doesn't eat them first.

    # WordPress / project lifecycle
    ("依赖未就绪，无法创建项目", "dependencies not ready, can't create project"),
    ("依赖未就绪，无法导入 WordPress 项目", "dependencies not ready, can't import WordPress project"),
    ("WordPress 核心已复制", "WordPress core copied"),
    ("创建 WordPress 项目失败", "Failed to create WordPress project"),
    ("创建 WordPress 项目", "Creating WordPress project"),
    ("WordPress 项目创建完成", "WordPress project created"),
    ("主题已导入", "Theme imported"),
    ("导入主题失败", "Theme import failed"),
    ("插件已导入", "Plugin imported"),
    ("导入插件失败", "Plugin import failed"),
    ("完整 WordPress 项目已导入", "Full WordPress project imported"),
    ("导入完整 WordPress 项目失败", "Failed to import full WordPress project"),
    ("WordPress 目录项目已导入", "WordPress directory project imported"),
    ("导入 WordPress 目录失败", "Failed to import WordPress directory"),
    ("项目已删除", "Project deleted"),
    ("删除项目失败", "Failed to delete project"),
    ("SQLite 插件未安装，跳过 db.php 检查", "SQLite plugin not installed, skipping db.php check"),
    ("db.php 不存在，正在生成...", "db.php missing, generating..."),
    ("db.php 未正确引用 SQLite 插件，重新生成", "db.php doesn't reference the SQLite plugin correctly, regenerating"),
    ("WordPress 已安装，跳过自动安装", "WordPress already installed, skipping auto-install"),
    ("WordPress 未安装，开始自动安装...", "WordPress not installed, starting auto-install..."),
    ("安装响应", "Install response"),
    ("安装响应未包含成功标志，可能安装未完成", "Install response missing success marker; install may be incomplete"),
    ("读取安装响应失败", "Failed to read install response"),
    ("WordPress 自动安装失败", "WordPress auto-install failed"),
    ("WordPress 自动安装请求完成", "WordPress auto-install request complete"),
    ("WordPress 安装验证成功", "WordPress install verification succeeded"),
    ("WordPress 安装验证: 仍重定向到 install.php", "WordPress install verification: still redirecting to install.php"),
    ("WordPress 安装验证异常", "WordPress install verification raised an exception"),
    ("WordPress 安装验证超时", "WordPress install verification timed out"),
    ("WordPress 自动安装异常", "WordPress auto-install raised an exception"),
    ("WordPress 运行时配置已应用", "WordPress runtime config applied"),
    ("WordPress 运行时配置失败", "WordPress runtime config failed"),
    ("应用 WordPress 运行时配置失败", "Failed to apply WordPress runtime config"),
    ("db.copy 已复制为 db.php", "db.copy copied to db.php"),
    ("db.copy 不存在，手动生成 db.php drop-in", "db.copy missing, generating db.php drop-in manually"),
    ("SQLite 插件已安装", "SQLite plugin installed"),
    ("wp-config.php 已生成", "wp-config.php generated"),
    ("跳过不安全的 zip 条目", "Skipping unsafe zip entry"),

    # Python runtime / health check
    ("Python 进程意外退出", "Python process exited unexpectedly"),
    ("Python 二进制", "Python binary"),
    ("PYTHONHOME 标准库目录不存在", "PYTHONHOME stdlib directory missing"),
    ("PYTHONHOME 标准库", "PYTHONHOME stdlib"),
    ("Python 版本验证通过", "Python version check passed"),
    ("安装 Python 依赖...", "Installing Python dependencies..."),
    ("pip install 失败，但 .pypackages 已携带", "pip install failed, but .pypackages already carries"),
    (" 个包，继续启动", " package(s); continuing startup"),
    ("启动 Python 服务器", "Starting Python server"),
    ("工作目录", "Working directory"),
    ("端口", "port"),
    ("框架", "framework"),
    ("=== Python 服务器启动诊断 ===", "=== Python server startup diagnostics ==="),
    (".pypackages 存在=", ".pypackages exists="),
    ("顶层数量=", "top-level count="),
    ("含文件=", "has files="),
    ("stdlib 存在=", "stdlib exists="),
    ("文件数=", "file count="),
    ("libpython so 存在=", "libpython so exists="),
    ("大小=", "size="),
    ("Python 服务器已启动", "Python server started"),
    ("Python 服务器启动超时", "Python server startup timed out"),
    ("启动 Python 服务器失败", "Failed to start Python server"),
    ("Python 服务器已停止", "Python server stopped"),
    ("停止 Python 服务器异常", "Python server stop raised an exception"),
    ("Python 项目文件已复制到", "Python project files copied to"),
    ("共 ", "total "),
    ("警告: 没有复制到任何文件!", "Warning: no files were copied!"),
    ("SAF 目录无效", "SAF directory invalid"),
    ("复制文件失败", "Failed to copy file"),
    ("SAF 项目文件已复制到", "SAF project files copied to"),
    ("警告: SAF 未复制到任何文件!", "Warning: SAF copied no files!"),
    ("Python --version 输出异常", "Python --version output is malformed"),
    ("Python --version 无输出", "Python --version produced no output"),
    (" (无 musl linker，二进制可能无法直接执行)", " (no musl linker, binary may not be directly executable)"),
    ("验证 Python 二进制失败", "Failed to verify Python binary"),
    ("Python 健康检查成功", "Python health check passed"),
    ("Python 服务器就绪", "Python server ready"),
    ("Python 健康检查稳定性重置", "Python health check stability reset"),

    # Node runtime / dependency
    ("使用 nativeLibraryDir Node", "Using nativeLibraryDir Node"),
    ("使用下载缓存 Node", "Using downloaded Node"),
    ("Node 占位路径（未安装）", "Node placeholder path (not installed)"),
    ("libnode.so 路径 (nativeLibraryDir)", "libnode.so path (nativeLibraryDir)"),
    ("libnode.so 路径 (下载缓存)", "libnode.so path (downloaded)"),
    ("libnode.so 在 nativeLibraryDir 与下载缓存中均不存在",
        "libnode.so is missing from both nativeLibraryDir and download cache"),
    ("libnode.so 与系统 page size ", "libnode.so is incompatible with system page size "),
    (" 不兼容，重写 PT_LOAD…", "; rewriting PT_LOAD…"),
    ("libnode.so ELF page-align patch 失败，dlopen 仍会报错",
        "libnode.so ELF page-align patch failed; dlopen will still fail"),
    ("libnode.so patch 完成但二次校验仍不兼容（patcher 算法疑似有 bug）",
        "libnode.so patch finished but a second pass still flags incompatibility (suspect patcher bug)"),
    ("libnode.so 已重打包到 ", "libnode.so re-packaged to "),
    ("Node.js 运行时下载完成", "Node.js runtime download complete"),
    ("下载 Node.js 运行时失败", "Failed to download Node.js runtime"),
    ("Node.js 依赖缓存已清理", "Node.js dependency cache cleared"),
    ("下载 Node.js 运行时 (共 ", "Downloading Node.js runtime ("),
    (" 个源)", " sources)"),
    ("Node.js 运行时已就绪", "Node.js runtime ready"),
    ("解压后未找到 ", "Not found after extraction: "),
    ("解压 Node.js 失败", "Failed to extract Node.js"),
    ("提取 ", "Extracting "),
    ("tryPatchPageAlignment: targetAlign 必须是 2 的幂",
        "tryPatchPageAlignment: targetAlign must be a power of two"),
    ("ELF patch 异常", "ELF patch exception"),
    ("patchElfPageSize: 仅支持 ELF64 LSB", "patchElfPageSize: only ELF64 LSB is supported"),
    ("patchElfPageSize: 没有 PT_LOAD segment", "patchElfPageSize: no PT_LOAD segment found"),
    ("patchElfPageSize: 文件已 ", "patchElfPageSize: file is already "),
    ("-aligned，无需重写", "-aligned, no rewrite needed"),
    ("patchElfPageSize: 计算出的目标大小过大", "patchElfPageSize: computed target size is too large"),
    ("patchElfPageSize: PT_LOAD@", "patchElfPageSize: PT_LOAD@"),
    (" 落盘后 p_align=", " on-disk p_align="),
    ("patchElfPageSize: 重写完成 ", "patchElfPageSize: rewrite complete "),
    (" 个 PT_LOAD 的 p_align 没落盘，dlopen 会失败",
        " PT_LOAD entries didn't persist p_align; dlopen will fail"),

    # ForcedRun accessibility / hardware controller
    ("启动强制运行防护", "Starting forced-run protection"),
    ("停止强制运行防护", "Stopping forced-run protection"),
    ("无 WRITE_SETTINGS 权限，无法控制系统亮度",
        "No WRITE_SETTINGS permission; can't control system brightness"),
    ("系统亮度已设置", "System brightness set"),
    ("辅助功能服务已连接", "Accessibility service connected"),
    ("拦截音量键", "Intercepting volume key"),
    ("拦截返回键", "Intercepting back key"),
    ("触摸屏蔽覆盖层已添加", "Touch-block overlay added"),
    ("添加触摸屏蔽覆盖层失败", "Failed to add touch-block overlay"),
    ("全黑屏覆盖层已添加", "Full-blackout overlay added"),
    ("添加全黑屏覆盖层失败", "Failed to add full-blackout overlay"),
    ("覆盖层已移除", "Overlay removed"),
    ("移除覆盖层失败", "Failed to remove overlay"),
    ("检测到屏幕关闭（电源键），立即唤醒",
        "Screen-off detected (power key); waking immediately"),
    ("屏幕关闭广播接收器已注册", "Screen-off broadcast receiver registered"),
    ("屏幕已强制唤醒", "Screen force-woken"),
    ("强制唤醒屏幕失败", "Failed to force-wake screen"),
    ("无 WRITE_SETTINGS 权限", "No WRITE_SETTINGS permission"),
    ("系统亮度已恢复", "System brightness restored"),
    ("设置系统亮度失败", "Failed to set system brightness"),
    ("窗口变化", "Window changed"),
    ("检测到离开应用", "Detected app leave"),
    ("，准备拉回", "; preparing to pull back"),
    ("执行拉回", "Pulling back"),
    ("拉回失败", "Pull-back failed"),
    ("备用拉回也失败", "Fallback pull-back also failed"),
    ("辅助功能服务被中断", "Accessibility service interrupted"),
    ("辅助功能服务销毁", "Accessibility service destroyed"),

    # Database migrations
    ("迁移 ", "Migration "),
    (" 跳过", " skipped"),
    (": 删除浏览器扩展字段", ": dropping browser-extension fields"),
    (" 完成", " complete"),
    (": 删除油猴脚本字段", ": dropping userscript fields"),
    (": 添加使用统计和健康检测表", ": adding usage-stats and health-check tables"),
    (": no schema changes", ": no schema changes"),
    (" blackTechConfig", " blackTechConfig"),
    (" disguiseConfig", " disguiseConfig"),
    (" 创建 app_categories", " creating app_categories"),
    (" categoryId", " categoryId"),
    (" autoStartConfig", " autoStartConfig"),
    (" forcedRunConfig", " forcedRunConfig"),

    # Generic shared phrases (kept short and unambiguous)
    ("尝试下载 ", "Attempting to download "),
    ("下载失败, ", "download failed, "),
    ("s 后重试 ", "s before retry "),
    ("，切换下一个源...", ", switching to next source..."),

    # ---------- safety net: catch-all single-word stems (LAST) ----------
    # These are intentionally minimal because broader catch-alls cause the
    # carry-over collisions we hit in round one.

    # ---------- Phase 4: clean up half-translated fragments ----------
    # The broad single-word rules above (失败 → failed etc.) created
    # mid-string collisions on previously untranslated long phrases. Each
    # entry below targets one specific surviving fragment so the rest of the
    # phrase can be translated in one shot. Order is from most specific
    # (longest) to most general.

    # WordPress fragments
    ("Install response未包含succeeded标志，可能安装未完成",
        "Install response missing succeeded marker; install may be incomplete"),
    ("WordPress 安装验证succeeded", "WordPress install verification succeeded"),
    ("WordPress 安装验证timed out", "WordPress install verification timed out"),
    (" 次)，继续加载", " attempts), continuing to load"),
    ("WordPress install verification raised an exception (尝试 ", "WordPress install verification raised an exception (attempt "),
    ("WordPress install verification: still redirecting to install.php (尝试 ", "WordPress install verification: still redirecting to install.php (attempt "),
    ("WordPress 已安装，skipping自动安装", "WordPress already installed, skipping auto-install"),
    ("WordPress 自动安装failed", "WordPress auto-install failed"),
    ("WordPress 运行时配置failed", "WordPress runtime config failed"),
    ("WordPress 核心ready", "WordPress core ready"),
    ("应用 WordPress 运行时配置failed", "Failed to apply WordPress runtime config"),
    ("所有 WordPress 依赖Download complete", "All WordPress dependencies downloaded"),
    ("下载 WordPress 核心 (total ", "Downloading WordPress core ("),
    ("读取Install responsefailed", "Failed to read install response"),
    ("SQLite 插件ready", "SQLite plugin ready"),
    ("SQLite 插件未安装，skipping db.php 检查", "SQLite plugin not installed, skipping db.php check"),
    ("解压 SQLite 插件failed", "Failed to extract SQLite plugin"),
    ("下载 SQLite 插件", "Downloading SQLite plugin"),
    ("解压 WordPress failed", "Failed to extract WordPress"),
    ("下载依赖failed", "Failed to download dependency"),
    ("依赖Cache cleared", "Dependency cache cleared"),
    ("删除项目failed", "Failed to delete project"),
    ("导入 WordPress 目录failed", "Failed to import WordPress directory"),
    ("导入主题failed", "Failed to import theme"),
    ("导入完整 WordPress 项目failed", "Failed to import full WordPress project"),
    ("导入插件failed", "Failed to import plugin"),

    # PHP runtime
    ("PHP 二进制ready", "PHP binary ready"),
    ("PHP 二进制仅支持 arm64-v8a, 当前设备", "PHP binary only supports arm64-v8a; current device"),
    ("PHP 二进制仍不可执行", "PHP binary still not executable"),
    ("PHP 二进制未就绪，返回 nativeLib 占位路径", "PHP binary not ready, returning nativeLib placeholder path"),
    ("PHP 未就绪：nativeLib=", "PHP not ready: nativeLib="),
    (", downloaded=", ", downloaded="),
    ("Not found after extraction: PHP 二进制", "PHP binary not found after extraction"),
    ("解压 PHP failed", "Failed to extract PHP"),
    ("下载 PHP 二进制 (total ", "Downloading PHP binary ("),
    ("下载 PHP 依赖failed", "Failed to download PHP dependency"),
    ("使用 nativeLibraryDir PHP", "Using nativeLibraryDir PHP"),
    ("使用下载的 PHP", "Using downloaded PHP"),
    ("使用下载的 PHP（旧布局）", "Using downloaded PHP (legacy layout)"),
    ("已修复 PHP 二进制执行权限", "Fixed PHP binary execute permission"),

    # Python runtime carry-overs
    ("=== Python 服务器Starting诊断 ===", "=== Python server startup diagnostics ==="),
    ("Python server ready (尝试 ", "Python server ready (attempt "),
    ("Python 健康检查succeeded (尝试 ", "Python health check passed (attempt "),
    ("Python 服务器Startingtimed out", "Python server startup timed out"),
    ("Python 服务器stopped", "Python server stopped"),
    ("Starting Python 服务器", "Starting Python server"),
    ("Starting Python 服务器failed", "Failed to start Python server"),
    ("PYTHONHOME stdlib: ", "PYTHONHOME stdlib: "),
    (" ($fileCount 文件)", " ($fileCount files)"),
    ("pip install failed，但 .pypackages 已携带", "pip install failed but .pypackages already carries"),
    (" 包，继续Starting", " packages; continuing startup"),
    ("验证 Python binaryfailed", "Failed to verify Python binary"),

    # Node fragments
    ("Node.js 运行时Download complete", "Node.js runtime download complete"),
    ("Node.js 运行时ready", "Node.js runtime ready"),
    ("Node.js 依赖Cache cleared", "Node.js dependency cache cleared"),
    ("解压 Node.js failed", "Failed to extract Node.js"),
    ("下载 Node.js 运行时 (total ", "Downloading Node.js runtime ("),
    ("下载 Node.js 运行时failed", "Failed to download Node.js runtime"),
    ("libnode.so ELF page-align patch failed，dlopen 仍会报错",
        "libnode.so ELF page-align patch failed; dlopen will still fail"),
    ("libnode.so path (下载缓存)", "libnode.so path (download cache)"),
    ("libnode.so re-packaged to ${pageSize}B 对齐", "libnode.so re-packaged to ${pageSize}B alignment"),
    ("patchElfPageSize: $corruptCount  PT_LOAD 的 p_align 没落盘，dlopen 会failed",
        "patchElfPageSize: $corruptCount PT_LOAD entries didn't persist p_align; dlopen will fail"),

    # Database migrations carry-overs
    ("Migration 27->28: 删除 docsSiteConfig 字段", "Migration 27->28: dropping docsSiteConfig field"),
    ("Migration 33->34: 添加 extensionEnabled 字段", "Migration 33->34: adding extensionEnabled field"),
    ("Migration 34->35: 补充 web_apps 索引", "Migration 34->35: adding web_apps indices"),
    ("Migration 35->36: 重建 web_apps 表以对齐当前本地结构",
        "Migration 35->36: rebuilding web_apps table to match current local schema"),
    (" 索引skipping", " index skipped"),

    # Native hardware controller
    ("Native hardware_control 库加载failed", "Native hardware_control library load failed"),
    ("Native hardware_control 库加载succeeded", "Native hardware_control library loaded"),
    ("CPU性能模式", "CPU performance mode "),
    ("CPU调频设置异常", "CPU governor setting exception"),
    ("IO优先级设置异常", "IO priority setting exception"),
    ("Detected app leave: $packageName, 准备拉回",
        "Detected app leave: $packageName, preparing to pull back"),
    ("System brightness set: $brightness (原值: $originalBrightness)",
        "System brightness set: $brightness (original: $originalBrightness)"),
    ("原生CPU压测Start exception", "Native CPU stress-test start exception"),
    ("原生CPU压测started", "Native CPU stress-test started"),
    ("原生CPU压测stopped", "Native CPU stress-test stopped"),
    ("原生CPU压测停止异常", "Native CPU stress-test stop exception"),
    ("原生亮度设置异常", "Native brightness setting exception"),
    ("原生持续震动Starting", "Native sustained vibration starting"),
    ("原生持续震动异常", "Native sustained vibration exception"),
    ("原生摩斯电码Start exception", "Native Morse code start exception"),
    ("原生摩斯电码Starting", "Native Morse code starting"),
    ("原生模式停止异常", "Native mode stop exception"),
    ("原生爆闪Start exception", "Native strobe start exception"),
    ("原生爆闪Starting", "Native strobe starting"),
    ("原生爆闪停止异常", "Native strobe stop exception"),
    ("原生自定义闪烁Start exception", "Native custom blink start exception"),
    ("原生自定义闪烁Starting", "Native custom blink starting"),
    ("原生资源已清理", "Native resources cleaned up"),
    ("原生资源清理异常", "Native resource cleanup exception"),
    ("原生闪光灯", "Native flashlight "),
    ("原生闪光灯控制异常", "Native flashlight control exception"),
    ("原生震动停止异常", "Native vibration stop exception"),
    ("原生震动异常", "Native vibration exception"),
    ("电源键注入异常", "Power-key injection exception"),
    ("输入注入异常", "Input injection exception"),
    ("进程优先级设置异常", "Process priority setting exception"),
    ("(间隔=", "(interval="),
    ("步, loop=", "steps, loop="),

    # ForcedRunManager
    ("Starting强制运行防护", "Starting forced-run protection"),
    ("强制运行保护已降级", "Forced-run protection degraded"),
    ("从持久化恢复倒计时", "Restoring countdown from persisted state"),
    (": 剩余 ", ": remaining "),
    (" (原结束时间 ", " (original end "),
    ("已设置倒计时结束闹钟", "Countdown end alarm scheduled"),
    ("已设置固定时间段结束闹钟", "Fixed-window end alarm scheduled"),
    ("已设置限时模式结束闹钟", "Time-bounded mode end alarm scheduled"),
    ("所有闹钟已取消", "All alarms cancelled"),
    ("精确闹钟权限不足，降级使用非精确闹钟",
        "Insufficient permission for exact alarm; falling back to inexact"),
    ("反序列化配置failed，清除持久化状态",
        "Config deserialise failed, clearing persisted state"),
    ("固定时间段已过期，清除", "Fixed window expired, clearing"),
    ("限时时段已过期，清除", "Time-bounded window expired, clearing"),
    ("倒计时已在进程死亡期间过期，清除",
        "Countdown expired while process was dead, clearing"),
    ("倒计时模式已在当前配置下结束，skipping重复自动Starting",
        "Countdown mode already ended for current config; skipping duplicate auto-start"),
    ("恢复倒计时", "Restoring countdown"),
    ("恢复固定时间段强制运行", "Restoring fixed-window forced-run"),
    ("恢复限时模式强制运行", "Restoring time-bounded forced-run"),
    ("无持久化状态需要恢复", "No persisted state to restore"),
    ("持久化状态已清除", "Persisted state cleared"),
    ("持久化状态损坏（缺少 config），清除",
        "Persisted state corrupt (missing config), clearing"),
    ("持久化配置已禁用，清除", "Persisted config disabled, clearing"),
    ("persistCountdown=false，skipping持久化",
        "persistCountdown=false, skipping persistence"),
    ("状态已持久化: mode=", "State persisted: mode="),

    # AppCloner
    ("APK 修改完成，大小: ", "APK modification complete, size: "),
    ("AndroidManifest.xml 修改后大小: ", "AndroidManifest.xml size after modification: "),
    ("AndroidManifest.xml 原始大小: ", "AndroidManifest.xml original size: "),
    ("getPackageArchiveInfo 返回 null，无法解析 APK",
        "getPackageArchiveInfo returned null; can't parse APK"),
    ("resources.arsc 修改后大小: ", "resources.arsc size after modification: "),
    ("resources.arsc 原始大小: ", "resources.arsc original size: "),
    ("修改 AndroidManifest.xml failed", "Failed to modify AndroidManifest.xml"),
    ("修改 resources.arsc failed", "Failed to modify resources.arsc"),
    ("克隆failed", "Cloning failed"),
    ("开始修改 APK...", "Modifying APK..."),
    ("开始克隆", "Starting clone"),
    ("开始签名...", "Signing..."),
    ("快捷方式配置: splashEnabled=", "Shortcut config: splashEnabled="),
    ("源 APK 不存在", "Source APK not found"),
    ("源 APK 大小", "Source APK size"),
    ("签名完成，最终大小", "Signing complete, final size"),
    ("解析克隆 APK succeeded: packageName=", "Parsed cloned APK: packageName="),
    ("调试解析克隆 APK 时发生异常", "Exception while parsing cloned APK"),
    ("新包名", "New package name"),

    # NativeBridge / WebView
    ("已Entering fullscreen模式", "Entered fullscreen mode"),
    ("已Exiting fullscreen模式", "Exited fullscreen mode"),
    ("屏幕亮度已设置为", "Screen brightness set to"),
    ("屏幕常亮", "Keep-screen-on"),
    ("屏幕方向已解锁", "Screen orientation unlocked"),
    ("屏幕方向已设置为", "Screen orientation set to"),
    ("屏幕方向已锁定", "Screen orientation locked"),
    ("锁定屏幕方向failed", "Failed to lock screen orientation"),
    ("解锁屏幕方向failed", "Failed to unlock screen orientation"),
    ("设置屏幕亮度failed", "Failed to set screen brightness"),
    ("设置屏幕方向failed", "Failed to set screen orientation"),
    ("请求通知权限failed", "Notification-permission request failed"),
    ("读取通知权限状态failed", "Failed to read notification-permission state"),
    ("通知权限不可用", "Notification permission unavailable"),
    ("打开应用failed", "Failed to open app"),
    ("打开链接failed", "Failed to open link"),
    ("拉回failed", "Pull-back failed"),
    ("备用拉回也failed", "Fallback pull-back also failed"),
    ("强制唤醒屏幕failed", "Failed to force-wake screen"),
    ("加载图标failed", "Failed to load icon"),
    ("保存文件failed", "Failed to save file"),
    ("创建快捷方式failed", "Failed to create shortcut"),
    ("下载视频failed", "Failed to download video"),
    ("获取剪贴板failed", "Failed to read clipboard"),
    ("显示网页通知failed", "Failed to show web notification"),
    ("清除页内查找failed", "Failed to clear in-page find"),
    ("页内查找failed", "In-page find failed"),
    ("页内查找跳转failed", "In-page find navigation failed"),
    ("复制文件failed: $destRelPath - ${e.message}",
        "Failed to copy file: $destRelPath - ${e.message}"),
    ("设置系统亮度failed", "Failed to set system brightness"),
    ("移除覆盖层failed", "Failed to remove overlay"),
    ("添加全黑屏覆盖层failed", "Failed to add full-blackout overlay"),
    ("添加触摸屏蔽覆盖层failed", "Failed to add touch-block overlay"),
    ("模式Vibration failed", "mode vibration failed"),

    # ---------- Phase 5: services / runtime / utility logger phrases ----------
    # NotificationPollingService / BackgroundRunService / floating window /
    # autostart receivers etc. — all developer-facing logcat-only.

    # PHP / Go / Node runtime status
    ("PHP 服务器启动超时", "PHP server startup timed out"),
    ("PHP 服务器就绪", "PHP server ready"),
    ("PHP 服务器已停止", "PHP server stopped"),
    ("PHP 服务器已启动", "PHP server started"),
    ("停止 PHP 服务器异常", "PHP server stop raised an exception"),
    ("健康检查 #", "Health check #"),
    ("启动 PHP 服务器失败", "Failed to start PHP server"),
    ("启动 PHP 服务器", "Starting PHP server"),
    ("提取路由服务器脚本失败", "Failed to extract router-server script"),
    ("路由服务器脚本已提取", "Router-server script extracted"),
    ("PHP 二进制", "PHP binary"),
    ("PHP 进程意外退出", "PHP process exited unexpectedly"),
    ("PHP 项目文件已复制到", "PHP project files copied to"),
    ("Go 服务器启动超时", "Go server startup timed out"),
    ("Go 服务器就绪", "Go server ready"),
    ("Go 服务器已停止", "Go server stopped"),
    ("Go 服务器已启动", "Go server started"),
    ("Go 进程意外退出", "Go process exited unexpectedly"),
    ("Go 项目文件已复制到", "Go project files copied to"),
    ("启动 Go 服务器失败", "Failed to start Go server"),
    ("启动 Go 服务器", "Starting Go server"),
    ("停止 Go 服务器异常", "Go server stop raised an exception"),
    ("检测到 Go 二进制", "Go binary detected"),
    ("Node.js 服务器就绪", "Node.js server ready"),
    ("Node.js 服务器已启动", "Node.js server started"),
    ("Node.js 已启动过（每个进程只能启动一次）",
        "Node.js already started (each process can only start it once)"),
    ("Node.js 线程异常", "Node.js thread exception"),
    ("Node.js 退出", "Node.js exited"),
    ("启动 Node.js 服务器 (子进程)", "Starting Node.js server (child process)"),
    ("启动 Node.js", "Starting Node.js"),
    ("停止 Node.js 服务器异常", "Node.js server stop raised an exception"),
    ("Node server 已经在跑，复用 port", "Node server already running, reusing port"),

    # libnode / JNI bridge
    ("libnode.so 加载失败", "libnode.so load failed"),
    ("libnode.so 加载成功", "libnode.so loaded"),
    ("libnode.so 已加载", "libnode.so already loaded"),
    ("libnode.so 未加载，无法启动", "libnode.so not loaded, can't start"),
    ("libnode.so 未找到", "libnode.so not found"),
    ("libnode.so 通过 System.loadLibrary 加载成功",
        "libnode.so loaded via System.loadLibrary"),
    ("System.loadLibrary(\\\"node\\\") 失败", "System.loadLibrary(\\\"node\\\") failed"),
    ("加载 libnode.so (dlopen)", "Loading libnode.so (dlopen)"),
    ("node_bridge JNI 库加载失败", "node_bridge JNI library load failed"),
    ("node_bridge JNI 库加载成功", "node_bridge JNI library loaded"),
    ("ensureDnsPatched 失败", "ensureDnsPatched failed"),
    ("handleStartServer 异常", "handleStartServer raised an exception"),
    (":nodejs 子进程 NodeService onCreate", ":nodejs child process NodeService onCreate"),
    (":nodejs 子进程 NodeService onDestroy", ":nodejs child process NodeService onDestroy"),
    ("收到 KILL_ENGINE，主动结束 :nodejs 进程，等待 Framework 重建",
        "Received KILL_ENGINE, terminating :nodejs process; waiting for framework restart"),
    ("回送 IPC 消息失败 (主进程可能已断开)",
        "Failed to send IPC message (main process may have disconnected)"),
    ("回送 SERVER_FAILED", "Sending back SERVER_FAILED"),
    ("IPC 回包失败 (主进程已断开?)",
        "IPC reply failed (main process disconnected?)"),

    # Go toolchain
    ("Go .deb 下载失败", "Go .deb download failed"),
    ("Go .deb 体积异常", "Go .deb size mismatch"),
    ("实际 ", "actual "),
    (" 字节，期望 ", " bytes, expected "),
    ("（容差 ±", " (tolerance ±"),
    ("）—— 可能镜像变更或下载损坏", ") — mirror may have changed or download corrupted"),
    ("Go .deb 解压完成: 复制 ", "Go .deb extraction complete: copied "),
    (" 项，跳过 ", " items, skipped "),
    (" 项（非 GOROOT 内容）。", " items (non-GOROOT content)."),
    ("Go binary DNS 路径补丁应用次数", "Go binary DNS-path patches applied"),
    ("Go verify 异常", "Go verify exception"),
    ("Go 工具链已就绪", "Go toolchain ready"),
    ("Go 工具链已就绪，跳过下载", "Go toolchain ready, skipping download"),
    ("Go 工具链当前仅支持 arm64-v8a，设备 ABI",
        "Go toolchain currently only supports arm64-v8a; device ABI"),
    ("Go 工具链缓存已清理", "Go toolchain cache cleared"),
    ("解 ", "Extracting "),
    (" ...", "..."),
    ("解压完成但 go binary 不可用: 路径=",
        "Extraction complete but go binary unusable: path="),
    (" 存在=", " exists="),
    (" 大小=", " size="),
    (" 可执行=", " executable="),
    ("应用内构建失败，将报告 binary 不可用",
        "In-app build failed; reporting binary as unavailable"),
    ("应用内构建成功", "In-app build succeeded"),
    ("安装 Go 工具链失败", "Failed to install Go toolchain"),
    ("symlink 解压失败", "symlink extraction failed"),
    ("symlink 跳过", "symlink skipped"),
    ("tar 前几条 entry 路径样本", "tar first-few entry path samples"),
    ("启动 Go 服务器", "Starting Go server"),

    # Translation (TranslateBridge)
    (" 翻译失败", " translation failed"),
    (" 连续失败 ", " consecutive failures: "),
    (" 次，降级到 ", " — falling back to "),
    ("Google 响应解析失败", "Google response parse failed"),
    ("LibreTranslate 响应解析失败", "LibreTranslate response parse failed"),
    ("Lingva 响应解析失败", "Lingva response parse failed"),
    ("MyMemory 响应解析失败", "MyMemory response parse failed"),
    ("所有翻译引擎均失败，返回原文", "All translation engines failed; returning original text"),
    ("手动切换翻译引擎", "Manually switching translation engine"),
    ("降级翻译成功，切换活跃引擎到", "Fallback translation succeeded; switching active engine to"),
    ("翻译执行失败", "Translation execution failed"),
    ("网络请求异常", "Network request exception"),

    # Floating window
    ("FloatingWindowService 已创建", "FloatingWindowService created"),
    ("FloatingWindowService 已销毁", "FloatingWindowService destroyed"),
    ("悬浮窗 SSL 错误", "Floating window SSL error"),
    ("悬浮窗下载请求", "Floating window download request"),
    ("悬浮窗加载真实 URL", "Floating window loaded real URL"),
    ("悬浮窗启动服务端运行时", "Floating window starting server-side runtime"),
    ("悬浮窗已关闭", "Floating window closed"),
    ("悬浮窗已启动", "Floating window started"),
    ("悬浮窗已恢复", "Floating window restored"),
    ("悬浮窗已显示", "Floating window shown"),
    ("悬浮窗已最小化", "Floating window minimised"),
    ("悬浮窗页面加载错误", "Floating window page load error"),
    ("关闭悬浮窗失败", "Failed to close floating window"),
    ("切换悬浮窗全屏失败", "Failed to toggle floating-window fullscreen"),
    ("最小化失败", "Failed to minimise"),
    ("更新窗口位置失败", "Failed to update window position"),
    ("更新窗口大小失败", "Failed to update window size"),
    ("更新透明度失败", "Failed to update opacity"),
    ("缩放窗口失败", "Failed to scale window"),
    ("授予 IME 焦点失败", "Failed to grant IME focus"),
    ("释放 IME 焦点失败", "Failed to release IME focus"),
    ("显示悬浮窗失败", "Failed to show floating window"),
    ("恢复窗口位置失败", "Failed to restore window position"),
    ("解析悬浮窗配置失败", "Failed to parse floating-window config"),
    ("服务端运行时停止失败", "Server-side runtime stop failed"),
    ("服务端运行时启动失败", "Server-side runtime start failed"),
    ("解析结果: appType=", "Parse result: appType="),

    # Background / polling / autostart services
    ("后台运行服务停止请求已发送", "Background-run service stop request sent"),
    ("后台运行服务创建", "Background-run service created"),
    ("后台运行服务启动", "Background-run service started"),
    ("后台运行服务启动请求已发送", "Background-run service start request sent"),
    ("后台运行服务销毁", "Background-run service destroyed"),
    ("守护服务创建", "Guard service created"),
    ("守护服务启动", "Guard service started"),
    ("守护服务销毁", "Guard service destroyed"),
    ("停止后台运行服务失败", "Failed to stop background-run service"),
    ("停止轮询通知服务失败", "Failed to stop polling-notification service"),
    ("startForeground 失败，服务无法启动", "startForeground failed; service can't start"),
    ("startForeground 失败", "startForeground failed"),
    ("已调度后台服务重启", "Background service restart scheduled"),
    ("已调度轮询服务重启", "Polling service restart scheduled"),
    ("无可恢复配置，跳过后台服务重启调度", "No restorable config; skipping background-service restart schedule"),
    ("无可恢复配置，跳过轮询服务重启调度", "No restorable config; skipping polling-service restart schedule"),
    ("启动轮询通知服务失败", "Failed to start polling-notification service"),
    ("弹出轮询通知", "Showing polling notification"),
    ("弹出轮询通知失败", "Failed to show polling notification"),
    ("轮询 URL 为空，服务无法启动", "Polling URL is empty; service can't start"),
    ("轮询请求失败", "Polling request failed"),
    ("轮询请求返回非 2xx", "Polling request returned non-2xx"),
    ("轮询通知服务停止请求已发送", "Polling-notification service stop request sent"),
    ("轮询通知服务创建", "Polling-notification service created"),
    ("轮询通知服务启动请求已发送", "Polling-notification service start request sent"),
    ("轮询通知服务已启动", "Polling-notification service started"),
    ("轮询通知服务已在运行", "Polling-notification service already running"),
    ("轮询通知服务已销毁", "Polling-notification service destroyed"),
    ("解析轮询结果失败", "Failed to parse polling result"),
    ("通知权限不可用", "Notification permission unavailable"),
    ("已在电池优化白名单中", "Already on battery-optimisation allowlist"),
    ("已请求忽略电池优化", "Battery-optimisation ignore requested"),
    ("请求忽略电池优化失败", "Failed to request battery-optimisation ignore"),
    ("服务已在运行", "Service already running"),

    # WakeLock
    ("WakeLock 已续期", "WakeLock renewed"),
    ("WakeLock 已获取", "WakeLock acquired"),
    ("WakeLock 已释放", "WakeLock released"),
    ("WakeLock 续期失败", "WakeLock renewal failed"),
    ("WakeLock 获取失败", "WakeLock acquire failed"),
    ("WakeLock 释放失败", "WakeLock release failed"),
    ("WakeLock 释放异常", "WakeLock release exception"),

    # Forced run / receiver / accessibility
    ("AlarmManager 触发：停止强制运行", "AlarmManager triggered: stopping forced-run"),
    ("ActivityManager 查询失败", "ActivityManager query failed"),
    ("UsageStatsManager 查询失败", "UsageStatsManager query failed"),
    ("启动强制运行: appId=", "Starting forced-run: appId="),
    ("结束强制运行: appId=", "Ending forced-run: appId="),
    ("强制运行已从持久化恢复", "Forced-run restored from persisted state"),
    ("强制运行已在运行中，忽略启动请求", "Forced-run already running; ignoring start request"),
    ("强制运行未在运行中，忽略结束请求", "Forced-run not running; ignoring stop request"),
    ("恢复强制运行状态失败", "Failed to restore forced-run state"),
    ("收到广播", "Broadcast received"),
    ("定时检查强制运行状态", "Periodic check of forced-run state"),
    ("定时检查：强制运行正常运行中", "Periodic check: forced-run is running normally"),
    ("定时检查：恢复了中断的强制运行", "Periodic check: restored an interrupted forced-run"),
    ("无持久化状态可恢复", "No persisted state to restore"),
    ("拉起目标 Activity 失败，尝试 Launch Intent",
        "Failed to launch target Activity; trying Launch Intent"),
    ("使用自身 LaunchIntent 拉起", "Launching with own LaunchIntent"),
    ("自身 LaunchIntent 也失败", "Own LaunchIntent also failed"),
    ("降级拉起也失败", "Fallback launch also failed"),
    ("目标 Activity 已拉起", "Target Activity launched"),
    ("moveTaskToFront 失败", "moveTaskToFront failed"),
    ("检测到离开应用", "Detected app leave"),
    (", 拉回中...", ", pulling back..."),

    # Autostart / boot / scheduled
    ("收到定时启动广播", "Scheduled-start broadcast received"),
    ("Shell 模式：今天(周", "Shell mode: today (day "),
    (")不在启动日期列表中，跳过", ") is not in the scheduled launch days; skipping"),
    (")在启动日期列表中，启动应用", ") is in the scheduled launch days; launching app"),
    ("Shell 模式：定时自启动未启用，跳过", "Shell mode: scheduled autostart disabled, skipping"),
    ("Shell 模式：延迟 ", "Shell mode: delaying "),
    ("ms 后启动开机自启动应用", "ms before launching boot-autostart app"),
    ("主应用模式：今天(周", "Main app mode: today (day "),
    ("主应用模式：延迟 ", "Main app mode: delaying "),
    ("ms 后启动应用 ", "ms before launching app "),
    ("主应用模式：无定时配置，跳过", "Main app mode: no schedule configured, skipping"),
    ("收到开机完成广播", "BOOT_COMPLETED broadcast received"),
    ("开机启动，检查强制运行状态", "Boot complete: checking forced-run state"),
    ("开机恢复：强制运行已恢复", "Boot recovery: forced-run restored"),
    ("开机恢复：无需恢复的强制运行状态", "Boot recovery: no forced-run state needs restoring"),
    ("收到应用更新广播，恢复闹钟调度", "App-update broadcast received; restoring alarm schedule"),
    ("应用更新后恢复闹钟失败", "Failed to restore alarms after app update"),
    ("收到时间变更广播", "Time-change broadcast received"),
    ("时间变更后重新调度闹钟失败", "Failed to reschedule alarms after time change"),
    ("定时启动处理异常", "Scheduled-start handling raised an exception"),
    ("开机自启动处理异常", "Boot-autostart handling raised an exception"),
    ("定时自启动 ", "Scheduled autostart "),
    ("开机自启动 ", "Boot autostart "),
    ("精确闹钟已设置", "Exact alarm set"),
    ("精确闹钟权限不可用，使用近似闹钟", "Exact alarm permission unavailable; using inexact alarm"),
    ("设置精确闹钟被拒绝，降级为近似闹钟", "Exact alarm denied; falling back to inexact alarm"),
    ("设置闹钟完全失败", "Alarm setting failed entirely"),
    ("定时闹钟已取消", "Scheduled alarm cancelled"),
    ("无法计算下一次启动时间", "Can't compute next launch time"),
    ("防重复调度：距上次调度不足 ", "Debounce: less than "),
    ("ms，跳过", "ms since last schedule, skipping"),

    # Cache / port manager / cookies / WebView
    ("Cookie 已清除", "Cookies cleared"),
    ("WebStorage 已清除", "WebStorage cleared"),
    ("WebView 缓存已清除", "WebView cache cleared"),
    ("WebView UA配置: userAgentMode=", "WebView UA config: userAgentMode="),
    ("历史记录已清除", "History cleared"),
    ("域名 ", "Domain "),
    (" 的 Cookie 已清除", " cookies cleared"),
    ("表单数据已清除", "Form data cleared"),
    ("清除 Cookie 失败", "Failed to clear cookies"),
    ("清除 WebStorage 失败", "Failed to clear WebStorage"),
    ("清除 WebView 缓存失败", "Failed to clear WebView cache"),
    ("清除历史记录失败", "Failed to clear history"),
    ("清除域名 Cookie 失败", "Failed to clear domain cookies"),
    ("清除表单数据失败", "Failed to clear form data"),
    ("清除目录失败", "Failed to clear directory"),
    ("清除缓存失败", "Failed to clear cache"),
    ("缓存超过阈值 (", "Cache exceeded threshold ("),
    (")\uff0c开始自动清理", "), starting auto-cleanup"),
    ("计算目录大小失败", "Failed to compute directory size"),

    # PortManager
    ("=== 端口分配详情 ===", "=== Port allocation details ==="),
    (" 范围端口已满，尝试通用范围", " range is full; trying general range"),
    ("分配端口 ", "Allocated port "),
    (" 给 ", " to "),
    (" (范围: ", " (range: "),
    ("/回退)", "/fallback)"),
    (" (首选)", " (preferred)"),
    ("无法为 ", "Can't allocate port for "),
    (" 分配端口，所有范围已满", "; all ranges are full"),
    ("已终止端口 ", "Killed process for port "),
    (" 关联的进程 (优雅退出)", " (graceful exit)"),
    ("强制终止端口 ", "Force-killed process for port "),
    (" 关联的进程", ""),
    ("终止端口 ", "Failed to kill process for port "),
    (" 进程失败", ""),
    ("注册端口 ", "Registering port "),
    (" 的进程 (PID: ", " process (PID: "),
    ("释放端口 ", "Releasing port "),
    (" (原使用者: ", " (previous owner: "),
    ("释放所有端口 (共 ", "Releasing all ports ("),
    (" 个)", ")"),
    ("清理僵尸端口 ", "Cleaning zombie port "),
    (", 存活: ", ", uptime: "),
    ("首选端口 ", "Preferred port "),
    (" 不可用，自动分配", " unavailable, auto-allocating"),

    # Asset decryption
    ("写入加密元数据 ", "Writing encrypted metadata "),
    ("写入明文 BGM", "Writing plaintext BGM"),
    ("写入明文 HTML 文件", "Writing plaintext HTML file"),
    ("写入明文启动画面", "Writing plaintext splash screen"),
    ("写入明文媒体文件", "Writing plaintext media file"),
    ("写入明文配置文件", "Writing plaintext config file"),
    ("加密 BGM", "Encrypting BGM"),
    ("加密 HTML 文件", "Encrypting HTML file"),
    ("加密元数据不存在或无效", "Encrypted metadata missing or invalid"),
    ("加密启动画面", "Encrypting splash screen"),
    ("加密媒体文件", "Encrypting media file"),
    ("加密配置文件", "Encrypting config file"),
    ("加载加密元数据成功", "Loaded encrypted metadata successfully"),
    ("加载加密资源", "Loading encrypted asset"),
    ("加载原始资源", "Loading raw asset"),
    ("十六进制字符串转换失败", "Hex string decode failed"),
    ("十六进制字符串长度不是偶数", "Hex string length is not even"),
    ("使用当前 APK 签名派生密钥", "Deriving key from current APK signature"),
    ("使用元数据中的签名哈希派生密钥", "Deriving key from metadata signature hash"),
    ("旧版 APK 兼容：使用元数据中的签名哈希派生密钥",
        "Legacy APK compatibility: deriving key from metadata signature hash"),
    ("获取密钥失败，使用当前应用签名派生密钥",
        "Key fetch failed; deriving from current app signature"),
    ("解密失败，尝试加载明文备份", "Decrypt failed; trying plaintext backup"),
    ("解密完成", "Decrypt complete"),
    ("解密资源", "Decrypting asset"),
    ("读取加密文件失败", "Failed to read encrypted file"),
    ("明文备份也不存在", "Plaintext backup also missing"),
    ("应用目录流式写入失败", "App-directory streaming write failed"),
    ("流式写入失败", "Streaming write failed"),
    ("流式保存到公共下载目录", "Streaming save to public Downloads directory"),
    ("流式保存到应用目录", "Streaming save to app directory"),
    ("流式保存完成", "Streaming save complete"),
    ("文件已保存", "File saved"),
    ("文件已保存到公共下载目录", "File saved to public Downloads directory"),
    ("文件已保存到应用目录", "File saved to app directory"),
    ("MediaStore 保存失败，尝试备用方案", "MediaStore save failed; trying fallback"),
    ("MediaStore 流式保存失败，尝试备用方案", "MediaStore streaming save failed; trying fallback"),

    # Backup / data export
    ("准备导出 ", "Preparing to export "),
    (" 个应用", " apps"),
    ("收集到 ", "Collected "),
    (" 个资源文件", " asset files"),
    ("无法打包本地数据", "Can't bundle local data"),
    ("无法打包资源文件", "Can't bundle asset file"),
    ("解压资源文件失败", "Asset extraction failed"),
    ("跳过不安全的备份路径", "Skipping unsafe backup path"),
    ("清理备份目录失败", "Failed to clean backup directory"),
    ("清理文件失败", "Failed to clean file"),
    ("读取到 ", "Read "),
    (" 个应用", " apps"),
    ("导入分类失败", "Failed to import category"),
    ("导入失败", "Import failed"),
    ("导入应用失败", "Failed to import app"),
    ("解析分类失败，已跳过一项", "Failed to parse category, skipping one item"),
    ("解析应用配置失败，已跳过一项", "Failed to parse app config, skipping one item"),
    ("恢复本地数据失败", "Failed to restore local data"),
    ("恢复扩展模块配置失败", "Failed to restore extension-module config"),
    ("扩展模块配置已恢复", "Extension-module config restored"),
    ("解析自定义 Headers 失败", "Failed to parse custom headers"),

    # Privacy / IsolationManager
    ("初始化隔离环境", "Initialising isolation environment"),
    ("指纹已重新生成", "Fingerprint regenerated"),
    ("加载指纹失败", "Failed to load fingerprint"),
    ("加载配置失败", "Failed to load configuration"),
    ("生成新指纹: UA=", "Generated new fingerprint: UA="),
    ("注入脚本", "Injecting script"),
    ("扩展模块: extensionModuleIds=", "Extension modules: extensionModuleIds="),
    ("设置 User-Agent", "Setting User-Agent"),
    ("设置环境变量失败", "Failed to set environment variable"),
    ("设置环境变量异常", "Setting environment variable raised an exception"),
    ("隔离数据已清除", "Isolation data cleared"),
    ("隔离环境未启用", "Isolation environment not enabled"),
    ("隔离脚本注入完成", "Isolation script injection complete"),

    # Shell mode
    ("加载配置文件失败", "Failed to load config file"),
    ("加载配置文件时发生严重错误", "Critical error loading config file"),
    ("尝试加载配置文件", "Attempting to load config file"),
    ("配置文件内容长度", "Config file content length"),
    ("配置无效: appType=", "Invalid config: appType="),
    ("配置有效，进入 Shell 模式", "Config valid; entering shell mode"),
    ("未找到 ", "Not found: "),
    ("，按主 app 模式运行", "; running in main-app mode"),
    ("读取 ", "Reading "),
    (" 失败", " failed"),
    ("获取 Shell 配置失败", "Failed to fetch shell config"),
    ("项目目录", "Project directory"),

    # Favicon
    ("从 Google Favicon 服务获取图标成功", "Fetched icon via Google Favicon service"),
    ("从 HTML 获取图标成功", "Fetched icon from HTML"),
    ("从 favicon.ico 获取图标成功", "Fetched icon via favicon.ico"),
    ("下载图标失败", "Icon download failed"),
    ("图标太小", "Icon too small"),
    ("图标已保存", "Icon saved"),
    ("开始获取网站图标", "Fetching site icon"),
    ("无效的图片", "Invalid image"),
    ("无法获取网站图标", "Can't fetch site icon"),
    ("无法解码图片", "Can't decode image"),
    ("解析 HTML 获取图标失败", "Failed to fetch icon by parsing HTML"),
    ("获取网站图标失败", "Site icon fetch failed"),

    # Encrypted APK builder
    ("执行命令", "Executing command"),
    (" ... (共 ", "... ("),
    (" 个参数)", " args)"),

    # Misc
    ("Native flashlight 控制异常", "Native flashlight control exception"),
    ("拉回失败", "Pull-back failed"),
    ("download failed, ${RETRY_DELAY_MS / 1000}s 后重试 ($attempt/$MAX_RETRY_PER_URL)",
        "download failed, retrying in ${RETRY_DELAY_MS / 1000}s ($attempt/$MAX_RETRY_PER_URL)"),
]


def parse_calls(text: str):
    pattern = re.compile(r"AppLogger\.[a-z]+\(")
    i = 0
    while True:
        m = pattern.search(text, i)
        if not m:
            return
        start = m.start()
        j = m.end()
        depth = 1
        in_str = False
        escape = False
        while j < len(text) and depth > 0:
            c = text[j]
            if escape:
                escape = False
            elif in_str:
                if c == "\\":
                    escape = True
                elif c == '"':
                    in_str = False
            else:
                if c == '"':
                    in_str = True
                elif c == "(":
                    depth += 1
                elif c == ")":
                    depth -= 1
            j += 1
        yield start, j
        i = j


CHINESE_RE = re.compile(r"[\u4e00-\u9fff]")
LITERAL_RE = re.compile(r'(?<!\\)"((?:\\.|[^"\\])*)"', re.DOTALL)


def translate_literal(literal: str) -> str:
    out = literal
    for cn, en in TRANSLATIONS:
        if cn in out:
            out = out.replace(cn, en)
    return out


def translate_call(call: str) -> str:
    def replace(match: re.Match) -> str:
        body = match.group(1)
        if not CHINESE_RE.search(body):
            return match.group(0)
        new_body = translate_literal(body)
        return '"' + new_body + '"'

    return LITERAL_RE.sub(replace, call)


def translate_file(path: str) -> int:
    with open(path, encoding="utf-8") as f:
        text = f.read()

    new_text_parts = []
    cursor = 0
    changes = 0
    for start, end in parse_calls(text):
        new_text_parts.append(text[cursor:start])
        original = text[start:end]
        translated = translate_call(original)
        if translated != original:
            changes += 1
        new_text_parts.append(translated)
        cursor = end
    new_text_parts.append(text[cursor:])
    new_text = "".join(new_text_parts)

    if new_text != text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_text)
    return changes


if __name__ == "__main__":
    paths = sys.argv[1:]
    if not paths:
        print("usage: log_translate.py <path> [<path> ...]", file=sys.stderr)
        sys.exit(2)
    for p in paths:
        n = translate_file(p)
        print(f"{p}: {n} call(s) updated")
