package com.webtoapp.core.aicoding.session

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import com.google.gson.reflect.TypeToken
import com.webtoapp.core.aicoding.files.ProjectFileManager
import com.webtoapp.util.GsonProvider
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map

private val Context.aicodingStore: DataStore<Preferences> by preferencesDataStore(name = "aicoding_sessions_v1")

class SessionStore(
    private val context: Context,
    private val files: ProjectFileManager
) {

    private val gson = GsonProvider.gson

    val sessionsFlow: Flow<List<AgentSession>> = context.aicodingStore.data.map { decode(it[KEY_SESSIONS]) }
    val currentSessionIdFlow: Flow<String?> = context.aicodingStore.data.map { it[KEY_CURRENT] }

    suspend fun create(activeSkillName: String?, title: String = ""): AgentSession {
        val session = AgentSession(activeSkillName = activeSkillName, title = title)
        context.aicodingStore.edit { p ->
            val list = decode(p[KEY_SESSIONS]).toMutableList()
            list.add(0, session)
            p[KEY_SESSIONS] = gson.toJson(list)
            p[KEY_CURRENT] = session.id
        }

        files.getSessionRoot(session.id)
        return session
    }

    suspend fun setCurrent(id: String) {
        context.aicodingStore.edit { it[KEY_CURRENT] = id }
    }

    suspend fun get(id: String): AgentSession? = sessionsFlow.first().firstOrNull { it.id == id }

    suspend fun delete(id: String) {
        context.aicodingStore.edit { p ->
            val list = decode(p[KEY_SESSIONS]).filter { it.id != id }
            p[KEY_SESSIONS] = gson.toJson(list)
            if (p[KEY_CURRENT] == id) p.remove(KEY_CURRENT)
        }
        files.deleteSession(id)
    }

    suspend fun rename(id: String, newTitle: String) = mutate(id) {

        it.copy(title = newTitle, titleAutoGenerated = false)
    }

    suspend fun setAutoTitle(id: String, newTitle: String): AgentSession? = mutate(id) { s ->
        if (!s.titleAutoGenerated) s else s.copy(title = newTitle)
    }

    suspend fun pin(id: String, pinned: Boolean) = mutate(id) { it.copy(pinned = pinned) }

    suspend fun setActiveSkill(id: String, skillName: String?) = mutate(id) {
        it.copy(activeSkillName = skillName)
    }

    suspend fun updateConfig(id: String, config: SessionConfig) = mutate(id) {
        it.copy(config = config)
    }

    suspend fun appendMessage(id: String, message: AgentMessage): AgentSession? {
        var captured: AgentSession? = null
        context.aicodingStore.edit { p ->
            val list = decode(p[KEY_SESSIONS]).toMutableList()
            val idx = list.indexOfFirst { it.id == id }
            if (idx < 0) return@edit
            var s = list[idx]

            if (s.title.isBlank() && message.role == AgentMessage.Role.USER) {
                s = s.copy(title = message.content.take(40).trim())
            }
            s = s.copy(messages = s.messages + message, updatedAt = System.currentTimeMillis())
            list[idx] = s
            captured = s
            p[KEY_SESSIONS] = gson.toJson(list)
        }
        return captured
    }

    suspend fun replaceMessages(id: String, messages: List<AgentMessage>): AgentSession? = mutate(id) {
        it.copy(messages = messages)
    }

    suspend fun truncateAt(id: String, messageId: String, keep: Boolean): AgentSession? = mutate(id) { s ->
        val idx = s.messages.indexOfFirst { it.id == messageId }
        if (idx < 0) return@mutate s
        val end = if (keep) idx + 1 else idx
        s.copy(messages = s.messages.take(end))
    }

    suspend fun recordPlan(sessionId: String, planSlug: String) = mutate(sessionId) { s ->
        val newSlugs = (s.planSlugs + planSlug).distinct()
        s.copy(planSlugs = newSlugs)
    }

    suspend fun clearAll() {
        val all = sessionsFlow.first().map { it.id }
        all.forEach { files.deleteSession(it) }
        context.aicodingStore.edit { p ->
            p.remove(KEY_SESSIONS)
            p.remove(KEY_CURRENT)
        }
    }

    private suspend fun mutate(id: String, block: (AgentSession) -> AgentSession): AgentSession? {
        var captured: AgentSession? = null
        context.aicodingStore.edit { p ->
            val list = decode(p[KEY_SESSIONS]).toMutableList()
            val idx = list.indexOfFirst { it.id == id }
            if (idx < 0) return@edit
            val updated = block(list[idx]).copy(updatedAt = System.currentTimeMillis())
            list[idx] = updated
            captured = updated
            p[KEY_SESSIONS] = gson.toJson(list)
        }
        return captured
    }

    private fun decode(raw: String?): List<AgentSession> {
        if (raw.isNullOrBlank()) return emptyList()
        return runCatching {
            gson.fromJson<List<AgentSession>>(raw, object : TypeToken<List<AgentSession>>() {}.type)
        }.getOrElse { emptyList() }
    }

    companion object {
        private val KEY_SESSIONS = stringPreferencesKey("sessions_v1")
        private val KEY_CURRENT = stringPreferencesKey("current_v1")
    }
}
