package com.webtoapp.core.aicoding.session

import java.util.UUID

data class AgentSession(
    val id: String = UUID.randomUUID().toString(),
    val title: String = "",

    val titleAutoGenerated: Boolean = true,

    val activeSkillName: String? = null,
    val messages: List<AgentMessage> = emptyList(),
    val config: SessionConfig = SessionConfig(),

    val planSlugs: List<String> = emptyList(),

    val pinned: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

data class SessionConfig(
    val textModelId: String? = null,
    val imageModelId: String? = null,
    val temperature: Float = 0.7f,
    val maxTurns: Int = 8,

    val customRules: List<String> = emptyList()
)

data class AgentMessage(
    val id: String = UUID.randomUUID().toString(),
    val role: Role,
    val content: String,
    val thinking: String? = null,

    val thinkingDurationMs: Long? = null,
    val toolCalls: List<RecordedToolCall> = emptyList(),

    val producedFiles: List<String> = emptyList(),

    val attachments: List<String> = emptyList(),

    val mentionedFiles: List<String> = emptyList(),
    val isError: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
) {
    enum class Role { USER, ASSISTANT, SYSTEM }
}

data class RecordedToolCall(
    val toolCallId: String,
    val name: String,
    val argumentsJson: String,
    val resultPreview: String,
    val ok: Boolean,

    val activity: String? = null
) {
    companion object {

        const val RUNNING_SENTINEL = "__running__"
    }
}
